import json,csv
R={r['Item_No']:r for r in csv.DictReader(open('/workspace/checkpoint-review/backup-pre-fullverify/verified-items.csv'))}
V='Verified'; VC='Verified with correction needed'; CV='Cannot verify, cut it'; OP='Opinion'
D={}
TAIL=' Tightened sourcing pass 2026-09-24: former Best_Source_URL (%s) removed; it was a news/fact-check page and in most cases an unrelated page inherited from a mismatched catalog duplicate.'
def s(i,v,url,st,fix='',notes=''):
    old=R[str(i)]['Best_Source_URL']
    D[str(i)]=dict(Verdict=v,Best_Source_URL=url,Source_Type=st,Fix_Needed=fix,Notes=(notes+TAIL%old).strip())
DOJP='https://www.justice.gov/opa/pr/leader-antifa-cell-members-north-texas-sentenced-100-years-prison-terrorist-attack-ice'
IAEA='https://www.iaea.org/sites/default/files/gov2026-50.pdf'
CBP='https://www.cbp.gov/newsroom/stats/cbp-enforcement-statistics'
AGM='https://www.justice.gov/d9/press-releases/attachments/2021/10/04/ag_memo_1.pdf'
J6='https://www.govinfo.gov/app/details/GPO-J6-REPORT'
s(3,OP,'','','Label Our view. The DOJ July 2025 memo does not tabulate passengers by party; "people from both parties\u2019 worlds" is characterization.','Characterization; no checkable figure.')
s(4,V,CBP,'government_data','','CBP: 10.83M nationwide encounters FY2021\u2013FY2024 (FY2021 began Oct. 2020 under Trump). HHS 1,475 figure: Senate PSI hearing Apr. 26, 2018.')
s(5,V,'https://supreme.justia.com/cases/federal/us/395/444/','court_opinion','','Brandenburg v. Ohio, 395 U.S. 444 (1969) correctly summarized.')
s(6,VC,AGM,'official_record','Say: "The National School Boards Association\u2019s Sept. 29, 2021 letter asked for federal help and invoked domestic terrorism. On Oct. 4, 2021, AG Garland directed the FBI and U.S. Attorneys to coordinate." Label the last sentence Our view.','AG memo Oct. 4, 2021 (justice.gov blocks automated fetch; loads in a browser).')
s(7,VC,IAEA,'official_record (IAEA)','Keep 440.9 kg up to 60% as of June 13, 2025 (GOV/2026/50, dated Sept. 1, 2026). Drop "Iran is the only non-weapon state at 60 percent" (not stated in GOV/2026/50) or cite an IAEA report that says it. Jeffries\u2019 words: cite the Congressional Record/video where said.','GOV/2026/50 para 27: 440.9 kg HEU up to 60% (432.9 kg verified).')
s(8,VC,IAEA,'official_record (IAEA)','Keep the IAEA figure; cite Schumer\u2019s and Khanna\u2019s words only as where the claim was made (link the original post/record). Label "Denying the enrichment is denying an inspection" as Our view.','GOV/2026/50 para 27.')
s(14,VC,'https://www.c-span.org/clip/white-house-event/user-clip-trump-doesnt-kid-about-suggesting-we-stop-testing/4888561','unedited_video','Keep quotes (Tulsa, June 20, 2020; "I don\u2019t kid," June 23, 2020). "No order cutting tests was issued" is a negative; say "No written order to reduce testing has been produced."','C-SPAN clip of unedited coverage (bot-blocked to curl).')
s(18,CV,'','','Remove. The only source is AP\u2019s own fact check about AP photos; under the tightened standard a news outlet cannot be the source for a fact, and a checker never confirms a case about its own outlet.','No primary record of the 2014 photo dates located.')
s(23,V,'https://oig.justice.gov/reports/review-four-fisa-applications-and-other-aspects-fbis-crossfire-hurricane-investigation','official_record (DOJ OIG)','','Horowitz report 20-012 (Dec. 9, 2019): 17 significant inaccuracies and omissions; Clinesmith altered email (pleaded guilty, 18 U.S.C. 1001, Aug. 2020).')
s(38,V,'https://archive.org/details/project-2025-mandate-for-leadership-heritage-foundation/','primary_document (the book)','','Mandate for Leadership title page: Paul Dans and Steven Groves, eds.')
s(48,VC,'https://www.fda.gov/news-events/press-announcements/fda-takes-key-action-fight-against-covid-19-issuing-emergency-use-authorization-first-covid-19','official_record (FDA)','Link the Dec. 11, 2020 FDA emergency use authorization release (the site links the Aug. 2021 full approval).','First EUA Dec. 11, 2020 (Pfizer-BioNTech), during Trump\u2019s term.')
s(53,VC,'https://www.fec.gov/files/legal/murs/7291/7291_01.pdf','official_record (FEC)','Keep the FEC fine (MUR 7291). The "Republican donor started opposition research" clause needs a primary cite (e.g., Durham report) or should be cut.','FEC MUR 7291: DNC and Hillary for America fined for reporting Fusion GPS payments as legal services.')
s(56,V,'https://www.justice.gov/archives/sco/file/1373816/dl','official_record (Special Counsel report)','','Manafort convicted Aug. 2018 (E.D. Va.) on 8 tax and bank-fraud counts; no conspiracy-with-Russia charge.')
s(57,V,'https://www.justice.gov/usao-dc/pr/roger-stone-found-guilty-obstruction-false-statements-and-witness-tampering','official_record (DOJ)','','Convicted Nov. 15, 2019: obstruction, five false statements, witness tampering. Commuted July 2020; pardoned Dec. 2020.')
s(59,V,'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1162/vote_116_2_00033.htm','official_record (Senate roll call)','','Acquittals Feb. 5, 2020 and Feb. 13, 2021 (https://www.senate.gov/legislative/LIS/roll_call_votes/vote1171/vote_117_1_00059.htm, 57\u201343, short of 67).')
s(61,VC,'https://supreme.justia.com/cases/federal/us/601/100/','court_opinion','Replace the dead site link (404) with the Trump v. Anderson opinion.','Trump v. Anderson, 601 U.S. 100 (2024).')
s(62,VC,J6,'official_record (House select committee report)','Say: "Rioters chanted \u2018Hang Mike Pence.\u2019 At 2:24 p.m. he posted that Pence \u2018didn\u2019t have the courage.\u2019" Link the J6 committee final report (committee record) instead of the rally video, which does not contain the post.','Rally video does not contain the 2:24 p.m. post.')
s(64,VC,J6,'official_record (House select committee report)','Link the 4:17 p.m. Jan. 6 video record, not the rally video; keep "go home in peace".','')
s(65,V,'https://www.documentcloud.org/documents/20500984-planning-and-execution-timeline-for-the-national-guards-involvement-in-the-january-6-2021-violent-attack-at-the-us-capitol/','official_record (DoD timeline, hosted copy)','','DoD timeline document.')
s(67,VC,'https://www.c-span.org/clip/campaign-2024/donald-trump-on-illegal-immigrants-poisoning-the-blood-of-our-country/5098439','unedited_video','Label "and it is ugly" as Our view.','Durham, N.H., Dec. 16, 2023.')
s(70,V,'https://www.hsgac.senate.gov/subcommittees/investigations/hearings/oversight-of-hhs-and-dhs-efforts-to-protect-unaccompanied-alien-children-from-human-trafficking-and-abuse/','official_record (Senate PSI hearing)','','Apr. 26, 2018 PSI hearing: HHS could not determine whereabouts of 1,475 children on follow-up calls to sponsors (page intermittently 503).')
s(71,VC,'https://www.justice.gov/archives/opa/pr/attorney-general-announces-zero-tolerance-policy-criminal-illegal-entry','official_record (DOJ)','Fix date: "Zero tolerance was announced April 6, 2018; DHS began referring all adult crossers in May 2018." Support "separations happened before that policy" with HHS OIG OEI-BL-18-00511 (Jan. 2019): https://oig.hhs.gov/reports/all/2019/separated-children-placed-in-office-of-refugee-resettlement-care/','Flores settlement 1997.')
s(76,V,'https://www.courtlistener.com/docket/65895581/carroll-v-trump/','court_filing','','Verdict form: sexual abuse (May 9, 2023); Judge Kaplan, July 19, 2023 opinion.')
s(87,CV,'','','Remove. No primary record of the 2018 NSC reorganization was located; the only support is a Reuters fact check (approved with caution, secondary only).','')
s(88,CV,'','','Remove. The only support is a memoir and news; the linked FDA page is unrelated. "No recording and no order in the file" is an unprovable negative.','')
s(92,CV,'','','Remove. Settlements are supported only by news coverage in this pass; no court docket linked.','')
s(99,VC,'https://www.cdc.gov/mmwr/volumes/70/wr/mm7031e2.htm','government_data (CDC MMWR)','Attribute the quote to where it was said (Walensky, MSNBC, Mar. 29, 2021). Replace "false when it was said" with "CDC data published July 30, 2021 showed vaccinated people could be infected and carry similar viral loads."','MMWR 70(31), Provincetown outbreak.')
s(105,VC,DOJP,'official_record (DOJ)','Keep DOJ facts (June 23, 2026; eight sentenced; 100 years for Benjamin Song, attempted murder of an Alvarado officer; combined 450 years). Link the House Democrats\u2019 Sept. 21, 2026 post only as where the claim was made. Label the last sentence Our view.','DOJ PR read via Wayback snapshot of Sept. 19, 2026.')
s(113,CV,'','','Remove. No record ("TRUTH") text and no primary source.','')
s(119,V,CBP,'government_data','Add: FY2021 began Oct. 1, 2020 under Trump.','CBP nationwide encounters FY2021\u2013FY2024: 10.83M.')
s(120,VC,DOJP,'official_record (DOJ)','Keep DOJ facts. Label "An idea does not throw a frozen bottle..." as Our view.','DOJ June 23, 2026: 8 sentenced, Song 100 years, combined 450 years. Attack July 4, 2025.')
s(121,VC,AGM,'official_record','Label the last sentence Our view or cite the NSBA Oct. 22, 2021 letter.','AG memo Oct. 4, 2021.')
s(122,VC,'https://www.politifact.com/article/2013/dec/12/lie-year-if-you-like-your-plan-you-can-keep-it/','fact_checker (record of its own designation)','Keep only as "PolitiFact named it its 2013 Lie of the Year" (PolitiFact is approved with caution; this is its own record of its own award). "The promise did not survive the statute" needs CMS/HHS data or Our-view label.','')
s(126,OP,'','','Label Our view, or cite CBO\u2019s Aug. 2022 estimate directly.','Former AP link was unrelated.')
s(127,OP,'','','Label Our view; cite the CNN town hall (July 21, 2021) only as where the words were said.','Former AP link was unrelated.')
s(128,OP,'','','Label Our view; cite the Sept. 9, 2016 speech transcript/video only as where the words were said.','Former AP link was unrelated.')
s(129,CV,'','','Remove the stenographer/apostrophe detail: supported only by AP reporting.','')
s(133,CV,'','','Remove unless unedited video of the June 23, 2018 remarks is linked (none located; the linked IAEA PDF is unrelated).','')
s(136,VC,IAEA,'official_record (IAEA)','Same as item 7.','GOV/2026/50 para 27.')
s(137,VC,'https://www.congress.gov/119/crec/2026/03/04/172/41/CREC-2026-03-04-house.pdf','official_record (Congressional Record)','Link Schumer\u2019s post only as where the claim was made; keep IAEA figure with GOV/2026/50 link.','')
s(139,VC,'https://www.cbo.gov/system/files/2025-08/61367-SNAP.pdf','official_record (CBO)','Confirm the 2.4 million figure against the CBO letter before publishing (cbo.gov blocks automated fetch).','CBO SNAP estimate for P.L. 119-21.')
s(144,V,'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1151/vote_115_1_00179.htm','official_record (Senate roll call)','','July 28, 2017, "skinny repeal" failed 49\u201351.')
s(148,VC,'https://www.supremecourt.gov/orders/courtorders/121120zr_p860.pdf','court_filing','Cite specific court records (e.g., Texas v. Pennsylvania, Dec. 11, 2020 order) rather than a generic statement.','')
s(153,V,'https://constitution.congress.gov/constitution/amendment-12/','constitution','','Electoral Count Reform Act of 2022 later codified the ministerial role.')
s(159,V,'https://www.manhattanda.org/wp-content/uploads/2023/04/Donald-J.-Trump-Indictment.pdf','court_filing','','34 counts; jury verdict May 30, 2024.')
s(165,V,'https://www.congress.gov/bill/111th-congress/house-bill/3200','official_record','','H.R. 3200 Sec. 1233, advance care planning consultation.')
s(166,OP,'','','Label Our view.','Rhetoric.')
s(188,VC,'https://www.congress.gov/bill/117th-congress/house-resolution/503','official_record','Label "is not a jury. It is a production." as Our view.','H.Res. 503 Sec. 2: Speaker appoints; Pelosi rejected Jordan and Banks July 21, 2021.')
s(190,CV,'','','Remove the factual claims or label the paragraph Our view; the committee home page does not document the footage releases.','')
s(191,V,'https://www.dhs.gov/archive/news/2022/08/24/following-hsac-recommendation-dhs-terminates-disinformation-governance-board','official_record (DHS)','','Terminated Aug. 24, 2022.')
s(194,VC,'https://www.congress.gov/bill/118th-congress/house-resolution/12','official_record','Attribute findings to the Select Subcommittee (a committee report, not a court). Link the report itself, not a press release.','')
s(196,VC,'https://trumpwhitehouse.archives.gov/wp-content/uploads/2019/09/Unclassified09.2019.pdf','official_record','Label "Looking into corruption ... is the job of the executive" as Our view.','Senate acquittal Feb. 5, 2020.')
s(199,V,'https://www.nycourts.gov/ipjudicialethicsopinions/23-54.htm','official_record','','')
s(200,V,'https://www.nycourts.gov/LegacyPDFS/press/PDFs/People%20v.%20DJT%20Jury%20Instructions%20and%20Charges%20FINAL%205-23-24.pdf','court_filing','','')
s(201,VC,'https://www.courtlistener.com/docket/7649164/stephanie-clifford-v-donald-j-trump/','court_filing','Keep the fee order. Cut the Avenatti statements and CrowdJustice totals (news only).','')
s(202,VC,'https://www.courtlistener.com/docket/65895581/carroll-v-trump/','court_filing','Keep filing dates (N.Y. CPLR 214-j window Nov. 24, 2022\u2013Nov. 24, 2023). Cut the Reid Hoffman funding clause (news only).','')
s(203,V,'https://www.nycourts.gov/reporter/3dseries/2025/2025_04756.htm','court_opinion','','')
s(204,V,'https://www.courtlistener.com/docket/67490071/united-states-v-trump/','court_filing','','Dismissed July 15, 2024.')
s(206,VC,'https://www.fultonclerk.org/','official_record (court clerk)','Link the Nov. 26, 2025 nolle prosequi order itself (clerk home page is not the record).','')
s(207,VC,'https://www.justice.gov/storage/durhamreport.pdf','official_record (DOJ)','Keep as is; label characterizations as Our view.','')
s(209,CV,'','','Remove: no primary record linked for the employment path (jury instructions are unrelated).','')
s(210,V,'https://www.congress.gov/118/meeting/house/117301/documents/HHRG-118-FD00-20240515-SD027-U27.pdf','official_record (House hearing exhibit)','','Wade invoices.')
s(211,VC,'https://www.justice.gov/archives/opa/speech/attorney-general-merrick-b-garland-delivers-remarks-appointment-special-counsel','official_record (DOJ)','Keep; DC case dismissed without prejudice Nov. 25, 2024.','')
s(212,V,'https://www.nycourts.gov/Reporter/pdfs/2022/2022_30538.pdf','court_opinion','','')
s(213,V,'https://www.foreignassistance.gov/','government_data','','FY2023 disbursements; FEMA SSP figures per OIG-26-04.')
s(217,V,'','internal_count (repo src/lib/ledgers.ts)','','Count of the site\u2019s own captions; no external source needed.')
s(623,VC,DOJP,'official_record (DOJ)','Cite DOJ, not AP: June 23, 2026, eight sentenced, combined 450 years; Song 100 years.','')
s(806,VC,DOJP,'official_record (DOJ)','Cite DOJ, not AP.','')
s(181,CV,'','','Keep "The Flores settlement is 1997" only with a court-record link; remove the 2014-photo sentence (supported only by AP).','Internal duplicate of 18.')
s(182,VC,AGM,'official_record','Same as item 6.','Internal duplicate of 6.')
json.dump(D,open('/workspace/checkpoint-review/fv/verdicts_ledger_resource.json','w'),indent=1)
print(len(D))
