from specs1 import w,CF
CSP='https://www.c-span.org/program/public-affairs-event/house-minority-leader-jeffries-on-democracy/679567'
SCH='https://www.c-span.org/clip/us-senate/user-clip-youve-released-the-whirlwind-and-you-will-pay-the-price--sen-chuck-schumer/4944670'
w('they-work-for-us',CF,["Clip 2 re-sourced from Fox News to C-SPAN's full program of the May 19, 2026 CAP IDEAS speech (quote wording not independently checked against the video)",
"Jeffries YouTube/X links and 'he posted it / YouTube title' removed (social media)","Schumer links moved from YouTube/CNN to the C-SPAN clip",
"Maxine Waters quotes cut (no unedited original video found; only third-party uploads)","Harris post kept as her own words, unlinked","Biden: the donor-call quote is kept only as what he acknowledged on camera to NBC's Lester Holt on July 15, 2024"],
[["He said it at a news conference about maps. He posted it. He put it in a YouTube title. C-SPAN kept the raw.","He said it at a news conference about maps. C-SPAN kept the raw."],
["[Jeffries YouTube — “Maximum Warfare Everywhere All The Time”](https://www.youtube.com/watch?v=0IVD7gE7-kg)\n\n[Jeffries on X](https://x.com/hakeemjeffries/status/2046754383707148505)\n",""],
["May 19, 2026. A progressive conference.","May 19, 2026. The Center for American Progress IDEAS conference."],
["Fox News has the video of that speech: [Jeffries, “break them”](https://www.foxnews.com/video/6396075535112)\n\nWrite-up with the same quotes: [Fox News](https://www.foxnews.com/politics/hakeem-jeffries-shredded-disgustingly-violent-call-dems-break-spirit-maga)","C-SPAN has the full speech: [House Minority Leader Jeffries on Democracy]("+CSP+")"],
["The camera did not misspeak. [YouTube](https://www.youtube.com/watch?v=yu-7L5W6Rew) · [CNN](https://www.cnn.com/videos/politics/2020/03/04/schumer-gorsuch-kavanaugh-supreme-court-abortion-lead-vpx.cnn)","The camera did not misspeak. [C-SPAN]("+SCH+")"],
["Maxine Waters, June 2018: if Trump cabinet members are seen in a restaurant, “you get out and you create a crowd and you push back on them… they are not welcome, anymore, anywhere.” [YouTube](https://www.youtube.com/watch?v=-1Fu3g1MGHY) April 2021, Minneapolis: “We’ve got to stay on the street… We’ve got to get more confrontational.” [YouTube](https://www.youtube.com/watch?v=tnNBvN4ZXms)\n\n",""],
["[The post](https://x.com/KamalaHarris/status/1267555018128965643)","The post is still on her account."],
["Joe Biden, July 8, 2024, to donors — later confirmed on camera to Lester Holt: “time to put Trump in the bull’s-eye.” He called it a mistake after the fact. The admission is the tape. [NBC](https://www.nbcnews.com/video/biden-says-it-was-a-mistake-to-use-bullseye-in-remarks-about-trump-214895685978)","Joe Biden, July 2024, told donors it was time to put Trump in the “bull’s-eye.” On July 15, 2024, he told NBC’s Lester Holt, on camera, that using the word was a mistake. The admission is the tape."]],
ourview=["He named electoral defeat","It is a demand","Politicians work for the American people"])
w('the-funnel',CF,["Foreign-aid totals corrected: ForeignAssistance.gov's current data show about $80.5 billion disbursed in FY2023 (not $71.9 billion); the USAID $43.8 billion share was not re-pulled and is cut",
"USAID OIG figures linked to the two May 2026 audit reports ($36 million cash assistance to four NGOs; 18 humanitarian awards, $650 million); '$25.9 billion audited' semiannual figure cut (not located)",
"OIG-26-04 link corrected","NED sentence restated: NED funds four core institutes, including the party-affiliated NDI and IRI"],
[["In fiscal 2023 the United States disbursed about **$71.9 billion** in foreign aid. USAID moved about **$43.8 billion** of that — three of every five dollars.","In fiscal 2023 the United States disbursed about **$80.5 billion** in foreign assistance, by ForeignAssistance.gov’s current data."],
["Cash assistance in the West Bank and Gaza: about **$36 million** in fiscal 2024 to four NGOs, with fraud risk USAID did not identify. Humanitarian awards in that theater: **$650 million**, eighteen awards, vetting that still left a diversion risk. The spring 2026 semiannual report: **$25.9 billion** audited, convictions, debarments, NGO officers sentenced for laundering grant money.","[Cash assistance in the West Bank and Gaza](https://oig.usaid.gov/sites/default/files/2026-05/Audit%20of%20USAID%20Cash%20Assistance%20to%20West%20Bank%20Gaza%20%20%289-000-26-002-P%29.pdf): about **$36 million** in fiscal 2024 to four NGOs, with key fraud risks USAID did not identify. [Humanitarian awards in that theater](https://oig.usaid.gov/sites/default/files/2026-05/Final%20Audit%20Report%20-%20West%20Bank%20and%20Gaza%20Partner%20Vetting%20Audit%20%288-294-26-003-P%29_0.pdf): **$650 million** across eighteen awards, with selective partner vetting that the auditor said could increase the risk of diversion."],
["That is taxpayer money into party-aligned shops.","NED funds four core institutes, including those two party-affiliated ones."]],
ourview=["Federal grant money is not supposed","Anyone who says"])
exec(open('followup_specs_twfu.py',encoding='utf-8').read())
