from specs1 import w,CF
w('they-want-a-new-constitution',CF,["DSA program quote confirmed on the live program page ('draft a new constitution, and create a democratic socialist republic'); the Nazi-program comparison and the conclusions are labelled Our view","H.J.Res. 105 (104th Congress) link moved to the GPO text (Hoekstra recall amendment, July 26, 1995)"],
[],ourview=["The National Socialist German Workers","Read the PDF","A faction that writes"])
w('who-got-paid',CF,["Smuggling-revenue figures cut ($13B 'DHS estimate' known only via a House committee page and InSight Crime; the Washington Post $4–12B figure is press-only)",
"546,255 unaccompanied children and '2 million gotaways' cut (committee fact sheet, not CBP data); southwest encounters re-sourced to DHS OHSS (8.73 million, FY2021–24)",
"Bonillo and George sentences linked to DOJ releases (hosted by DHS OIG); Mexican officials' indictment dated and sourced (SDNY, unsealed April 29, 2026)",
"Cuellar pardon sourced to the DOJ pardon warrant (Dec. 2, 2025); the $200,000 laundering amount cut (press-only)",
"'65,000 child-welfare reports' and 'cartel revenue exploded' cut (no primary record); FY2021 caveat added"],
[["DHS's own estimate, cited by House Homeland Security and by InSight Crime: human smuggling into the United States was generating as much as $13 billion a year by 2021 — Biden's first year. The Washington Post, November 2024: $4 billion to $12 billion a year as a top income stream. ILO's global trafficking number — about $150 billion worldwide — is a different ledger. Those numbers stay on different ledgers. The border product","This journal will not print a smuggling-revenue figure it cannot trace to a government record, and the ones in circulation trace to committee pages and press accounts. The border product"],
["CBP recorded 546,255 unaccompanied children at the southwest border since FY2021, on top of 8.72 million southwest encounters and about 2 million known gotaways. Somebody collected on every one of those bodies.","[DHS’s statistics office](https://ohss.dhs.gov/khsm/cbp-encounters) counts 8.73 million southwest border encounters in fiscal 2021–24 (fiscal 2021 began in October 2020). Our view: somebody collected on those crossings."],
["Diego Bonillo, 15 years. Leonard Darnell George, 23 years, bribes to pass drugs and people.","[Diego Bonillo](https://www.oig.dhs.gov/sites/default/files/assets/pr/2025/dojpr-111325-former-customs-and-border-protection-officer-sentenced-allowing-drug-laden-vehicles.pdf), 15 years. [Leonard Darnell George](https://www.oig.dhs.gov/sites/default/files/assets/pr/2024/dojpr-102524-customs-and-border-protection-officer-sentenced-receiving-bribes-allow-drug-laden.pdf), 23 years, bribes to pass drugs and people."],
["April 2026: the United States indicted ten current and former Mexican officials — Morena party — for aiding Sinaloa trafficking.","April 29, 2026: [federal prosecutors in Manhattan](https://www.dea.gov/press-releases/2026/04/29/governor-sinaloa-and-nine-current-and-former-mexican-officials-face-drug) unsealed charges against the governor of Sinaloa and nine other current and former Mexican officials for aiding Sinaloa Cartel trafficking. The charges are allegations."],
["Two of his advisers pleaded guilty to laundering more than $200,000 of the Mexican-bank money. Trump later pardoned Cuellar.","Two of his associates pleaded guilty in the case. Trump [pardoned Cuellar and his wife](https://www.justice.gov/pardon/media/1419976/dl?inline=) on December 2, 2025."],
["Encounters exploded. Cartel revenue exploded. 65,000 child-welfare reports sat in a drawer. Then","Encounters exploded. Then"]],
ourview=["Somebody collected.","The political tie","Who got paid:"])
w('defund-ice-is-the-tell',CF,["False claim cut: the party did not 'lose hundreds of thousands of children inside a federal program'; DHS OIG-24-46 found ICE could not monitor the locations of all released unaccompanied children (32,000+ failed to appear; 291,000+ never served a Notice to Appear)",
"'7,300 reports in the ignored pile' cut (no primary record)","Grassley roundtable claims attributed to Sen. Grassley's office (a politician's press release, not an independent record)"],
[["lost hundreds of thousands of children inside a federal program,","released tens of thousands of children whom ICE, per its own [inspector general](https://www.oig.dhs.gov/sites/default/files/assets/2024-08/OIG-24-46-Aug24.pdf), could not keep track of,"],
["The 7,300 reports in the ignored pile are not a subplot. They are the plot.","The ignored reports are not a subplot. They are the plot."],
["Democrats refused Grassley's whistleblower roundtable. They opposed his bills","Sen. Grassley’s office says Democrats refused his whistleblower roundtable and opposed his bills"],
["- Grassley — Democrats refused the whistleblower roundtable; opposed contractor and rule bills — https://www.judiciary.senate.gov/press/rep/releases/new-hhs-data-confirms-biden-harris-admin-placed-tens-of-thousands-of-migrant-children-with-unvetted-sponsors-declined-recommended-home-studies\n","- DHS OIG-24-46 — ICE monitoring of unaccompanied children — https://www.oig.dhs.gov/sites/default/files/assets/2024-08/OIG-24-46-Aug24.pdf\n"],
["- DHS — ICE and HSI locating children; backlog of ignored reports —","- DHS — ICE and HSI locating children —"]],
ourview=["Defund ICE is all the proof","They use Epstein","When a mayor forbids","Democrats refused","Sen. Grassley"])
w('the-whole-bill',CF,["Budget Act wording corrected: the 1974 Act set October 1 as the start of the fiscal year and a timetable; the Act does not itself name twelve bills (there are twelve regular bills today)","Urban Institute $32–34 trillion figure cut (think-tank estimate, not a primary record)"],
[["It is twelve money bills the 1974 Budget Act already required by October 1","It is twelve regular money bills due by October 1, the fiscal-year start the 1974 Budget Act set"],
[" Medicare for all names the money — Urban Institute already put extra federal cost near $32–34 trillion over ten years. If the number is different, show the arithmetic."," Medicare for all names the money and shows the arithmetic."],
["Statute they already wrote: Congressional Budget Act of 1974. Twelve bills by October 1.","Statute they already wrote: Congressional Budget Act of 1974, which set the October 1 fiscal year. Twelve regular bills by that date."],
["- Urban Institute — single-payer extra federal cost ~$34T / 10 years — https://www.urban.org/urban-wire/dont-confuse-changes-federal-health-spending-national-health-spending\n",""]],
ourview=["This is not a street","They show a paragraph"])
