import json
from specs1 import w,CF
d=json.load(open('essay_edits/the-whole-bill.json')); d['ourview']=[x for x in d['ourview'] if x!='They show a paragraph']; json.dump(d,open('essay_edits/the-whole-bill.json','w'),indent=1,ensure_ascii=False)
w('the-pool',CF,["Only the President's own announcement is kept as fact (Truth Social post, Sept. 18, 2026, cited as where the claim was made); badge deactivation, Secret Service and pool-rotation details cut (reported only by the affected outlets and wire services)"],
[["Friday, September 18, 2026, the Oval said CNN, MS NOW, and Politico were barred from the White House, effective immediately. Saturday morning the badges failed. Secret Service took them. Monday the television pool rotation — ABC, CBS, CNN, NBC, Fox, a decades-old share of one camera — dropped CNN from the Monday assignment. That is the event.","Friday, September 18, 2026, the President announced on his own social-media account that CNN, MS NOW, and Politico were barred from the White House. The outlets say their reporters were turned away the next day; this journal has not seen an official record of the enforcement yet."],
["Friday they barred CNN, MS NOW, and Politico from the White House.","Friday the President said CNN, MS NOW, and Politico are barred from the White House."]],
ourview=["The other ledger is the tape","This journal does not need a badge","A credential is not a throne"])
w('they-dont-debate-they-flag','Cleared as-is',[],[],ourview=["That accusation is false","Reports were filed","A republic only works","Politicians talk for an hour","We will not print"])
w('they-ran-it-anyway',CF,["Schiff dates separated: on March 20, 2017 he read Steele-dossier allegations at a public hearing; the 'more than circumstantial evidence' line was a separate March 2017 TV interview (as H.Res. 630 itself records)",
"H.Res. 630 described accurately: a censure resolution House Republicans introduced in October 2019, which the House tabled; it is quoted as their claim, not as a finding",
"Horowitz report link corrected to the OIG's live PDF"],
[["On March 20, 2017 — months into the first term — the ranking Democrat on House Intelligence told the public the evidence of collusion was more than circumstantial.","On March 20, 2017 — two months into the first term — the ranking Democrat on House Intelligence read Steele-dossier allegations into a public hearing, and that same month he said in a television interview that he had “more than circumstantial evidence” of collusion."],
["The [Congressional Record](https://www.congress.gov/congressional-record/volume-165/issue-163/house-section/article/H8153-5), in H.Res. 630, later named those years: false accusations of collusion spread for more than two years; a March 2017 claim of more than circumstantial evidence.","House Republicans’ censure resolution, H.Res. 630 (October 2019, tabled by the House), put their charge in the [Congressional Record](https://www.congress.gov/congressional-record/volume-165/issue-163/house-section/article/H8153-5): false accusations of collusion spread for more than two years, including that March 2017 claim."]],
ourview=["The country was told the opposite"])
w('they-published-the-replacement','Cleared as-is',["DSA quotes confirmed against the live program and the September 2026 PDF"],[],ourview=["That cuts both ways","A prosecutor still has to prove"])
w('they-hold-it-by-the-blade',CF,["§ 2383 bullet corrected: no one was charged under the insurrection statute, but hundreds were charged with other felonies, including seditious conspiracy","Oyez links replaced with the opinions"],
[["18 U.S.C. § 2383 is the statute they did not file.","18 U.S.C. § 2383 is the statute they did not file; prosecutors charged other felonies instead, including [seditious conspiracy](https://www.law.cornell.edu/uscode/text/18/2384)."]],
ourview=["A republic uses the document","The Constitution is not the enemy"])
