from specs14 import dropl
from specs1 import w
w('it-does-not-fit','Held',["Urban Institute, Mercatus/Blahous, CRFB and Cato estimates and every figure derived from them cut (think-tank estimates, not official records)",
"CBO date corrected: February 2026, not March","'Congress has never scored the bill' corrected to 'CBO has not scored a specific Medicare for All bill'","Bipartisan Policy Center debt line replaced with Treasury's Debt to the Penny"],
[["Medicare for All is not a slogan. It is $32–34 trillion in extra federal spending in ten years — more than a full year of everything America produces — on a Treasury that already cannot close a $1.9 trillion hole.","Medicare for All is not a slogan. It is a bill with no official score, on a Treasury that already cannot close a $1.9 trillion hole."],
["Congress has never scored the bill. Think tanks have. The left-of-center Urban Institute already did the arithmetic they will not put on a slide: taking private insurance off the table and writing every hospital check from Washington adds about $32 trillion to $34 trillion in extra federal spending over ten years. Charles Blahous at Mercatus, using Sanders’s own bill, put the floor at $32.6 trillion even if every promised ‘saving’ comes true. The Committee for a Responsible Federal Budget put the range at $25 trillion to $35 trillion. Those are studies. Congress never sent","CBO has not scored a specific Medicare for All bill. Congress never sent"],
["CBO, March 2026.","[CBO, February 2026](https://www.cbo.gov/publication/61882)."],
["Bipartisan Policy Center, August 2026: gross federal debt is in sight of $40 trillion.","[Treasury](https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/): gross federal debt passed $40 trillion on August 18, 2026."],
["Medicare, the program they want to clone onto every American, already spent about $1.2 trillion in 2025 covering the old.","Medicare, the program they want to clone onto every American, already covers the old."],
[" DSA puts it on the same poster as reparations and a jobs guarantee. Cato stacked that program at $71 trillion to $212 trillion in ten years. There are only ten years in the window. That is not a platform. That is a confession that the private economy is the target."," DSA puts it on the same poster as reparations and a jobs guarantee."],
["Medicare for all names the money — Urban’s $32–34 trillion extra federal, or another number with the table attached, with the table attached.","Medicare for all names the money, with the table attached."],
["CBO has net interest doubling in a decade under current law — before Medicare for All. Add $3 trillion-plus a year in new federal outlays and the Treasury","CBO has net interest doubling in a decade under current law — before Medicare for All. Add trillions a year in new federal outlays and the Treasury"]],
ourview=["Not with a speech","Democrats who run on this"],
held_reason="The essay's central number (Urban Institute's $32–34 trillion), the Mercatus and CRFB ranges, the CRFB pay-for table and the Cato stack are think-tank estimates, not official records; every paragraph built on them is cut. What remains is the CBO baseline and the demand for a score. An editor must decide whether that is still an essay, or wait for an official CBO/JCT score.")
dropl('it-does-not-fit',["- $34 trillion","- The low Urban figure","The talking point is always the same","CRFB asked the only adult","- A 32 percent","- A 25 percent","- A 42 percent","- $7,500 per person","- Double every federal","- Cut 80 percent","- Or add 105 percent","CRFB was explicit","- Urban Institute","- Blahous","- CRFB","- Bipartisan Policy Center","### The number, in English","### How they would have to take it"])
w('the-check-they-will-not-write','Held',["Darity/Brookings, Forbes, Cato and Urban figures and all arithmetic built on them cut (think-tank and press estimates)","California $800 billion / $1.2 million per person / Newsom lines and the $12 million budget line cut (sourced to Politico and AP; no task-force report or budget act linked)",
"Evanston/DOJ 2026 sentence cut (no DOJ filing located)","Cato Forbes-400 $6.6 trillion cut","H.R. 40 wording corrected ('a reparations study bill introduced in every Congress since 1989'); cosponsor count dropped","Civil Liberties Act kept ($20,000 per eligible surviving internee); '$1.6 billion' total dropped"],
[["The advocates’ own number is $10–16 trillion. The Treasury does not have it.","The Treasury does not have the money."],
["H.R. 40 has been introduced since 1989.","A reparations study bill, now [H.R. 40](https://www.congress.gov/bill/118th-congress/house-bill/40), has been introduced in every Congress since 1989."],
["Ayanna Pressley ran it again on January 3, 2025, with ninety-six cosponsors.","Ayanna Pressley ran it again in 2025."],
[" Washington State Democrats put ‘implementation’ into a platform in June 2026 — after Juneteenth, on a weekend, in a room of delegates. That is the calendar. Not budget week. Not the Budget Committee. The weekend the cameras want a moral. California proved the rest. Gavin Newsom signed a task force, took the applause, and when the economists put $1.2 million per person on the table he would not write it. The 2024 budget set aside $12 million for ‘reparations legislation.’ Twelve million is a press release. It is not a program. The pattern"," The pattern"],
["The Civil Liberties Act of 1988 paid about $20,000 to living Japanese Americans who had been interned — a documented class, a finite roll, a bill of roughly $1.6 billion.","The [Civil Liberties Act of 1988](https://www.congress.gov/bill/100th-congress/house-bill/442) paid $20,000 to each eligible surviving Japanese American internee — a documented class, a finite roll."],
[" A Treasury payment whose only ticket is race is the fact pattern already in court in Evanston, Illinois — a $25,000 housing program the Justice Department moved to halt in 2026 as unconstitutional."," A Treasury payment whose only ticket is race runs straight into it."],
["CBO: $5.6 trillion in, $7.4 trillion out, $1.9 trillion hole, debt in sight of $40 trillion. Confiscating the net worth of the 400 richest Americans — about $6.6 trillion in 2025, per Cato — does not cover Darity’s floor. It does not cover Cato’s low DSA reparations line. The check,","[CBO](https://www.cbo.gov/publication/61882): $5.6 trillion in, $7.4 trillion out, $1.9 trillion hole; [Treasury](https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/): debt past $40 trillion. The check,"],
["What it cannot do is add a $16 trillion racial outlay on top of a $34 trillion health outlay and call the sum justice.","What it cannot do is add a trillion-dollar racial outlay on top of an unscored health outlay and call the sum justice."]],
ourview=["It comes back every cycle","Because it is cheap","A study cannot be opposed","Even if a court","This journal will not deny","The Hearing’s demand","An honest comparison"],
held_reason="The essay's money case — Darity's $10–16 trillion, the Cato and Urban stacks, California's $800 billion and $1.2 million figures — rests on think-tank estimates and press reports; all of it is cut, along with the unlocated Evanston/DOJ claim. What remains (H.R. 40's history, the Civil Liberties Act comparison, the equal-protection argument, CBO's baseline) may not carry the title claim. Editor decision required.")
dropl('the-check-they-will-not-write',["### The advocates’ own numbers","William Darity is the economist","- $16 trillion","- Stack it on","- Cato’s read","- California’s unofficial","- Darity / Brookings","- CNBC","- Forbes","- Cato","- H.R. 40, 119th","- POLITICO","- AP —"])
