import csv,json
IF='https://ifcncodeofprinciples.poynter.org/profile/'
rows=[
dict(Name='PolitiFact',Lean_Note='Poynter Institute (nonprofit); criticized from the right',
 IFCN_Status='Current (Verified Signatory; renewals accepted 2017-04-15 through 2026-03-13)',IFCN_URL=IF+'politifact',
 Corrections_Policy='Yes: in "Principles of the Truth-O-Meter" (corrections section)',Corrections_Policy_URL='https://www.politifact.com/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/',
 Corrections_Log='Yes: "Corrections and Updates" tag page',Corrections_Log_URL='https://www.politifact.com/corrections-and-updates/',
 Documented_Rating_Reversals='(1) Sept 2020 "Pants on Fire" rating that a lab-made SARS-CoV-2 claim was a "debunked conspiracy theory" was pulled from its database on May 17, 2021 with an editor\'s note calling the claim "unsupported by evidence and in dispute" (lab-leak). (2) 2015 Rubio nuclear-warheads fact-check changed from Pants on Fire to Half True after PolitiFact misheard the quote. (3) Oct 2020 Hunter Biden laptop coverage called the NY Post story "unconfirmed"; a June 14, 2021 article said "over time, there has been less doubt that the laptop did in fact belong to Hunter Biden" (an update, not a formal correction). (4) Apr 2019 context article on "very fine people" reproduces full transcript (no reversal needed).',
 Reversal_URLs='https://politifact.com/li-meng-yan-fact-check/ ; https://api.politifact.com/factchecks/2015/nov/14/marco-rubio/rubio-north-korea-has-over-two-dozen-nukes/ ; https://politifact.com/factchecks/2020/oct/20/facebook-posts/fact-checking-unproven-claims-about-hunter-biden-a/ ; https://politifact.com/article/2021/jun/14/donald-trumps-i-was-right-about-everything-fact-ch/',
 Funding_Transparency='Yes: "Who pays for PolitiFact" lists funders above 5% (Meta, TikTok) and grants by year; Meta US third-party program ended Jan 2025',Funding_URL='https://www.politifact.com/who-pays-for-politifact/',
 Methodology='Yes: published Truth-O-Meter principles and rating definitions',Methodology_URL='https://www.politifact.com/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/',
 Outcome='Approved with caution',Caution_Note='Withdrew a Trump-era, politically salient lab-leak "Pants on Fire" rating (May 2021). Cite only as "Independently confirmed by PolitiFact" where our own primary-source check already stands on its own; never for contested scientific or anonymous-source questions.',
 Rationale='PolitiFact meets every structural test: current IFCN signatory, published corrections policy and correction tag, disclosed funders, and published methodology. Its record includes a documented withdrawal of a high-profile Trump-era rating (the Sept 2020 lab-leak "Pants on Fire," pulled May 17, 2021) and a documented rating change after misquoting a speaker (Rubio, 2015). It did correct openly, which the policy requires, but the lab-leak episode shows that ratings built on expert consensus rather than primary records can flip. So it is approved only as secondary confirmation after our own primary-source verification.'),
dict(Name='FactCheck.org',Lean_Note='Annenberg Public Policy Center, University of Pennsylvania (nonprofit)',
 IFCN_Status='Current (Verified Signatory; renewals 2017-05-16 through 2026-05-20)',IFCN_URL=IF+'factcheck.org',
 Corrections_Policy='Yes: "Correction Policy" on Our Process page',Corrections_Policy_URL='https://www.factcheck.org/our-process/',
 Corrections_Log='Partial: corrections and updates are dated at the bottom of each article; no central log page located (/about/corrections/ returns 404)',Corrections_Log_URL='',
 Documented_Rating_Reversals='(1) Lab-leak: Sept 17, 2020 article "Report Resurrects Baseless Claim that Coronavirus Was Bioengineered" was not retracted but got an "Update, May 21, 2021" saying the origin "remains unknown" and a June 29, 2021 update; the May 2020 Wuhan-lab-funding article got the same update. (2) Aug 8, 2024 correction in "FactChecking the First Harris/Walz Rally": it had first said overall violent crime rose 2016-2020, then corrected using the FBI 2022 data (the correction relates to catalog case #186). (3) Hunter Biden laptop, Oct 2020: described the laptop as "purportedly belonging to" Hunter Biden and called the NY Post Ukraine story a "false narrative" on the Shokin firing. No formal correction located.',
 Reversal_URLs='https://www.factcheck.org/2020/09/report-resurrects-baseless-claim-that-coronavirus-was-bioengineered/ ; https://www.factcheck.org/2020/05/trump-spreads-distorted-claim-on-wuhan-lab-funding/ ; https://www.factcheck.org/2024/08/factchecking-the-first-harris-walz-rally/ ; https://www.factcheck.org/2020/10/social-media-posts-dredge-up-baseless-child-trafficking-conspiracy-theory/',
 Funding_Transparency='Yes: detailed quarterly and annual funding list, including Meta third-party program money 2017-2025 (FY2025 $258,320) and Google/YouTube; says it takes no union, partisan, or advocacy money',Funding_URL='https://www.factcheck.org/our-funding/',
 Methodology='Yes: Our Process page',Methodology_URL='https://www.factcheck.org/our-process/',
 Outcome='Approved with caution',Caution_Note='Its lab-leak "baseless" framing was softened by updates rather than corrected. Its Aug 2024 crime-rate correction shows it self-corrects. Use only as secondary confirmation after our primary check, and not on COVID-origin questions.',
 Rationale='FactCheck.org meets every structural test: current IFCN signatory, published correction policy, the most granular funding disclosure of any checker reviewed, and a published process. Corrections are dated in each article, but there is no central log. Its record shows open corrections (Aug 2024 crime data). It also shows 2020 lab-origin articles that labeled a disputed hypothesis "baseless" and were only updated in 2021, not retracted. Approved as secondary confirmation after our own verification, with the COVID-origin caveat.'),
dict(Name='Snopes',Lean_Note='Snopes Media Group (for-profit)',
 IFCN_Status='Current (Verified Signatory). Gap in record: accepted 2017, 2018, then not again until 2022-08-03 (lapsed about 2019-2022); latest 2025-07-11',IFCN_URL=IF+'snopes.com',
 Corrections_Policy='Yes: corrections policy on Transparency page, including how rating changes are disclosed',Corrections_Policy_URL='https://www.snopes.com/transparency/',
 Corrections_Log='Partial: "Retracted" tag archive; corrections noted in articles',Corrections_Log_URL='https://www.snopes.com/tag/retracted/',
 Documented_Rating_Reversals='(1) Aug 2021: co-founder and CEO David Mikkelson found to have plagiarized news outlets. Snopes senior management apologized, found 54 plagiarized posts in its internal review, and retracted them (AP and NYT reported 60). (2) "Very fine people": Snopes did not rate the claim until June 20, 2024 (False), about 7 years after it began circulating, then added an editors\' note on June 21, 2024 saying Trump\'s characterization of the rally was wrong. The rating stood.',
 Reversal_URLs='https://www.snopes.com/2021/08/13/apology-from-senior-management/ ; https://apnews.com/article/technology-business-arts-and-entertainment-8254cd876d91d04a79e53ebac9f358e5 ; https://www.snopes.com/fact-check/trump-very-fine-people/',
 Funding_Transparency='Partial: Disclosures and Transparency pages describe ownership and revenue sources (ads, memberships, platform contracts); no itemized dollar amounts located',Funding_URL='https://www.snopes.com/disclosures/',
 Methodology='Yes: published rating definitions',Methodology_URL='https://www.snopes.com/fact-check-ratings/',
 Outcome='Approved with caution',Caution_Note='Top-leadership integrity failure (plagiarism by CEO, 54-60 retractions), a lapsed IFCN period (about 2019-2022), and no itemized funding. Cite only articles published after Aug 2021 or that we re-read in full, only as confirmation after our primary check.',
 Rationale='Snopes is a current IFCN signatory with a published corrections policy, a retraction archive, and rating definitions. Its documented record includes a serious integrity failure at the top (the founder-CEO plagiarism scandal, with dozens of posts retracted in 2021) and a lapse in IFCN verification. Its funding disclosure gives no dollar figures. On Trump claims, it reached the correct transcript-based conclusion on "very fine people," but only in 2024. Approved only as secondary confirmation, with extra scrutiny.'),
dict(Name='AP Fact Check',Lean_Note='Associated Press (nonprofit cooperative)',
 IFCN_Status='Current (Verified Signatory; 2017-05-25 through 2026-05-20)',IFCN_URL=IF+'ap-fact-check',
 Corrections_Policy='Yes: AP News Values and Principles ("When we\'re wrong, we must say so as soon as possible")',Corrections_Policy_URL='https://www.ap.org/about/news-values-and-principles/telling-the-story/',
 Corrections_Log='No central public log located; corrections appear as editor\'s notes on stories',Corrections_Log_URL='',
 Documented_Rating_Reversals='No reversed or retracted AP fact-check rating on a Trump claim located in our search. Minor documented corrections: Oct 19, 2020 AP Fact Check misidentified the network (Fox Business Network) and corrected via editor\'s note; Oct 2025 fact focus republished to correct an ACA eligibility description.',
 Reversal_URLs='https://apnews.com/article/ap-fact-check-trump-virus-taxes-biden-3d7fb045c2b12c0a79552424f3f54b20',
 Funding_Transparency='Partial: AP is a member cooperative; fact-check unit participated in Meta program until 2023 (not itemized on a fact-check page)',Funding_URL='https://www.ap.org/about/',
 Methodology='Partial: AP Fact Check hub plus News Values; no separate rating scale',Methodology_URL='https://apnews.com/ap-fact-check',
 Outcome='Approved with caution',Caution_Note='No central corrections log and no itemized fact-check funding page. Several catalog cases involve AP itself as the outlet that made the error (e.g., #29, #80, #229, #236, #237); never cite AP as confirmation of a case about AP.',
 Rationale='AP is a current IFCN signatory with a published newsroom-wide corrections standard. We found no documented reversal of an AP fact-check rating on a Trump claim, only minor labeled corrections. It falls short on two structural tests: no central public corrections log, and no fact-check-specific funding disclosure. Because AP is itself the subject of several catalog cases, it is barred from confirming any case that concerns AP.'),
dict(Name='Reuters Fact Check',Lean_Note='Thomson Reuters (publicly traded)',
 IFCN_Status='Current (Verified Signatory; 2020-02-07 through 2025-04-23)',IFCN_URL=IF+'reuters',
 Corrections_Policy='Yes: detailed corrections, refile and update policy with advisory lines at the top of articles',Corrections_Policy_URL='https://www.reuters.com/fact-check/about/',
 Corrections_Log='Partial: corrected checks are re-promoted to the top of the fact-check home page; no standing log located',Corrections_Log_URL='',
 Documented_Rating_Reversals='No reversed rating on a Trump claim located in our search. Note: Reuters (news desk, not the fact-check unit) withdrew a Nov 2019 story on 100,000 children in US migration detention (catalog #106) and withdrew an Apr 7, 2025 Hassett tariff-pause story (catalog #59).',
 Reversal_URLs='',
 Funding_Transparency='Yes: discloses Meta, TikTok and LinkedIn fact-checking contracts',Funding_URL='https://www.reuters.com/fact-check/about/',
 Methodology='Yes: selection criteria and verdict definitions published',Methodology_URL='https://www.reuters.com/fact-check/about/',
 Outcome='Approved with caution',Caution_Note='IFCN renewal last accepted 2025-04-23, which may be due. Never cite Reuters as confirmation of a case in which Reuters itself erred (#59, #106, #248).',
 Rationale='Reuters Fact Check publishes a clear corrections policy, verdict definitions, and platform funding contracts, and is an IFCN signatory. We located no reversal of a Reuters fact-check rating on a Trump claim. The caution reflects the absence of a standing corrections log and the fact that the Reuters news desk is itself a subject of catalog cases, which creates a conflict for those rows.'),
dict(Name='Washington Post Fact Checker',Lean_Note='The Washington Post (Nash Holdings/Bezos)',
 IFCN_Status='Listed as Verified Signatory, but last accepted renewal was 2024-08-23. Chief writer Glenn Kessler left July 31, 2025 and no successor was located',IFCN_URL=IF+'the-washington-post-fact-checker',
 Corrections_Policy='Yes: WaPo newsroom policies; About The Fact Checker page (loads, but content was only partially retrievable)',Corrections_Policy_URL='https://www.washingtonpost.com/politics/2019/01/07/about-fact-checker/',
 Corrections_Log='No central log located',Corrections_Log_URL='',
 Documented_Rating_Reversals='(1) May 20, 2025: Kessler "re-examined three fact checks" after a NY Post editorial ("Everyone makes mistakes - which we quickly try to correct"). (2) The WaPo news desk (not the Fact Checker) added a June 2021 correction to its Feb 2020 Cotton lab-leak "debunked" article (catalog #72) and corrected the Frances Watson call quotes (catalog #60). (3) The column effectively ended July 31, 2025 (Kessler\'s final column).',
 Reversal_URLs='https://www.washingtonpost.com/politics/2025/05/20/biden-fact-checker-new-york-post/ ; https://www.washingtonpost.com/politics/2025/07/31/fact-checker-falsehoods-glenn-kessler/',
 Funding_Transparency='Partial: part of the WaPo newsroom; no fact-check-specific funding disclosure',Funding_URL='',
 Methodology='Yes: Pinocchio scale described on About page',Methodology_URL='https://www.washingtonpost.com/politics/2019/01/07/about-fact-checker/',
 Outcome='Approved with caution',Caution_Note='Archive only: cite only fact checks published before Aug 1, 2025. No central corrections log. Never cite for cases where the Washington Post itself is the outlet at fault.',
 Rationale='The Fact Checker has a long-published rating methodology and was an IFCN signatory, but its last accepted IFCN assessment is from Aug 2024, and the column lost its editor in July 2025 with no successor located. Its pages were only partially retrievable to us, and it has no central corrections log or unit-level funding disclosure. It is usable only for archived pre-Aug-2025 checks, only as secondary confirmation, and never for rows about the Post.'),
dict(Name='USA TODAY Fact Check',Lean_Note='Gannett (publicly traded)',
 IFCN_Status='Lapsed (Expired Signatory; last accepted 2024-06-18)',IFCN_URL=IF+'usa-today',
 Corrections_Policy='Yes: stated in "USA TODAY Fact Check: Standards and methodology" (per search result; direct fetch of that page from our box returned 404 or blocked)',Corrections_Policy_URL='https://www.usatoday.com/story/news/factcheck/2020/02/12/fact-check-guidelines-usa-today/4735217002/',
 Corrections_Log='Partial: "Corrections & Clarifications" notes in articles',Corrections_Log_URL='',
 Documented_Rating_Reversals='Documented rating changes after publication: Aug 2021 backpack check changed from False to True; Jan 2021 Super Bowl colors check changed to Missing Context. None located on a Trump claim.',
 Reversal_URLs='https://www.usatoday.com/story/news/factcheck/2021/08/04/fact-check-viral-image-altered-show-sexual-message-backpack/5461452001/ ; https://www.usatoday.com/story/news/factcheck/2021/01/27/fact-check-super-bowl-lv-chiefs-bucs-logos-same-primary-pantone-color/4276067001/',
 Funding_Transparency='Partial: Gannett newsroom; Meta partnership disclosed in articles; no itemized page located',Funding_URL='',
 Methodology='Yes (standards and methodology page)',Methodology_URL='https://www.usatoday.com/story/news/factcheck/2020/02/12/fact-check-guidelines-usa-today/4735217002/',
 Outcome='Approved with caution',Caution_Note='IFCN status expired (June 2024 was the last acceptance). We could not load the methodology page directly from our box. Documented False-to-True rating flips on non-political claims.',
 Rationale='USA TODAY has published standards and appends correction notes, including disclosed rating changes. Its IFCN verification has lapsed, its funding is not itemized, and we could not load its standards page directly. It is approved only as secondary confirmation, and the lapsed IFCN status is noted on every use.'),
dict(Name='Lead Stories',Lean_Note='Lead Stories LLC (for-profit)',
 IFCN_Status='Current (Verified Signatory; 2018-04-09 through 2026-05-20)',IFCN_URL=IF+'lead-stories',
 Corrections_Policy='Yes',Corrections_Policy_URL='https://leadstories.com/corrections-policy.html',
 Corrections_Log='Yes: Corrections archive ("overview of all our articles with corrections")',Corrections_Log_URL='https://leadstories.com/corrections/',
 Documented_Rating_Reversals='Dec 2021: The BMJ\'s editors publicly called Lead Stories\' Facebook fact-check of a BMJ investigation (Pfizer trial data integrity) "inaccurate, incompetent and irresponsible." Lead Stories defended the check in Jan 2022 and did not retract it. This is a documented unresolved dispute with a peer-reviewed journal. No reversal on a Trump claim located.',
 Reversal_URLs='https://leadstories.com/analysis/2022/01/context-matters-why-lead-stories-fact-checked-the-bmj.html ; https://www.bmj.com/content/375/bmj.n2635/rr-80',
 Funding_Transparency='Yes: financial-information page; revenue predominantly from Meta (ended April 2025) and ByteDance/TikTok',Funding_URL='https://leadstories.com/financial-information-funding-sources.html',
 Methodology='Yes: How we work',Methodology_URL='https://leadstories.com/how-we-work.html',
 Outcome='Approved with caution',Caution_Note='Revenue is heavily concentrated in platform contracts (Meta, ByteDance). Documented unresolved BMJ dispute. Use only for viral-fabrication cases (AI video, fake posts) as confirmation after our own check.',
 Rationale='Lead Stories meets all structural tests (current IFCN signatory, corrections policy, public corrections archive, funding page, methodology). Its record includes a prominent unresolved dispute with The BMJ over a "missing context" style label on accurate reporting, and its revenue depends heavily on platform contracts. Approved as secondary confirmation, mainly for viral-hoax items.'),
dict(Name='Check Your Fact (Daily Caller)',Lean_Note='Right-leaning parent (wholly owned for-profit subsidiary of The Daily Caller, Inc.)',
 IFCN_Status='Lapsed (Expired Signatory; last accepted 2024-03-13)',IFCN_URL=IF+'check-your-fact',
 Corrections_Policy='Yes',Corrections_Policy_URL='https://checkyourfact.com/corrections/',
 Corrections_Log='No central log located',Corrections_Log_URL='',
 Documented_Rating_Reversals='None located in our search (a search limitation, not proof that none exist).',
 Reversal_URLs='',
 Funding_Transparency='Yes (qualitative): funded by Daily Caller general news budget and ads, partially by Meta; majority owner Neil Patel named',Funding_URL='https://checkyourfact.com/about-us/',
 Methodology='Yes: four-verdict system (true, false, misleading, unsubstantiated)',Methodology_URL='https://checkyourfact.com/methodology/',
 Outcome='Approved with caution',Caution_Note='IFCN status expired (March 2024 was the last acceptance), no corrections log, and the parent outlet is partisan-leaning. Same caution level as USA TODAY for the lapsed status.',
 Rationale='Check Your Fact publishes a corrections policy, methodology, and qualitative funding and ownership disclosure. Its IFCN verification has lapsed, and it has no corrections log. We found no documented rating reversals, but our search was limited. Applying the same criteria as USA TODAY (also lapsed), it is approved with caution as secondary confirmation only.'),
dict(Name='The Dispatch Fact Check',Lean_Note='Center-right (The Dispatch Media)',
 IFCN_Status='Current (Verified Signatory; 2020-05-15 through 2025-07-29; a further application is pending)',IFCN_URL=IF+'the-dispatch-fact-check',
 Corrections_Policy='Not located on a dedicated fact-check page in our search (thedispatch.com/fact-check/ returned 404); IFCN verification implies one exists',Corrections_Policy_URL='',
 Corrections_Log='Not located',Corrections_Log_URL='',
 Documented_Rating_Reversals='None located in our search. Operational: after Meta ended its US program (Jan 2025), editor Steve Hayes said The Dispatch would continue fact-checking. Reporting indicates the dedicated section largely stopped updating after Oct 2025.',
 Reversal_URLs='https://thedispatch.com/article/fact-checking-meta-zuckerberg-dispatch/',
 Funding_Transparency='Partial: subscriber-funded outlet; Meta partnership disclosed',Funding_URL='https://thedispatch.com/article/fact-checking-meta-zuckerberg-dispatch/',
 Methodology='Not located (fact-check hub 404)',Methodology_URL='',
 Outcome='Rejected',Caution_Note='Could not locate a published corrections policy or methodology page. Re-vet if those pages are found.',
 Rationale='The Dispatch Fact Check is a current IFCN signatory. Under our identical criteria, though, we must be able to locate the checker\'s own published corrections policy and methodology, and its fact-check hub now returns 404 with neither page found. The section also appears largely dormant since late 2025. This is a documentation failure, not a finding of inaccuracy. It can be re-vetted and approved if the policies are produced.'),
dict(Name='AFP Fact Check',Lean_Note='Agence France-Presse (French public-status news agency)',
 IFCN_Status='Current (Verified Signatory; 2018-01-09 through 2026-09-15)',IFCN_URL=IF+'afp-fact-check',
 Corrections_Policy='Yes: in AFP Fact-Checking Stylebook ("Errors must be immediately and transparently corrected")',Corrections_Policy_URL='https://factcheck.afp.com/afp-fact-checking-stylebook',
 Corrections_Log='Yes: dedicated corrections page per language (per IFCN assessment); our box received 403 from factcheck.afp.com',Corrections_Log_URL='https://factcheck.afp.com/corrections',
 Documented_Rating_Reversals='None on a Trump claim located in our search.',
 Reversal_URLs='',
 Funding_Transparency='Yes (per IFCN assessment and AFP disclosures); platform contracts (Meta, TikTok) disclosed',Funding_URL='https://factcheck.afp.com/How-we-work',
 Methodology='Yes: How we work (requires at least two independent sources and prefers primary sources)',Methodology_URL='https://factcheck.afp.com/How-we-work',
 Outcome='Approved',Caution_Note='Our box is blocked by the site (403). Catalog links to AFP use web.archive.org copies.',
 Rationale='AFP meets every criterion: current IFCN signatory (renewed Sept 2026), a published corrections rule and a dedicated corrections log, a methodology that requires two independent sources and prefers primary material, and disclosed platform funding. We located no documented reversal of a rating on a Trump claim. Approved as secondary confirmation.'),
dict(Name='Full Fact',Lean_Note='UK charity',
 IFCN_Status='Current (Verified Signatory; 2017-03-22 through 2026-08-26)',IFCN_URL=IF+'full-fact',
 Corrections_Policy='Yes: Feedback & corrections page',Corrections_Policy_URL='https://fullfact.org/about/feedback/',
 Corrections_Log='No central public log located (fullfact.org/corrections/ returns 404)',Corrections_Log_URL='',
 Documented_Rating_Reversals='None located in our search. Full Fact rarely covers US/Trump claims and is not cited in the catalog.',
 Reversal_URLs='',
 Funding_Transparency='Yes: itemized funders with amounts (e.g., Meta £342,712 and £353,475; Google.org)',Funding_URL='https://fullfact.org/about/funding/',
 Methodology='Yes: How we fact check',Methodology_URL='https://fullfact.org/how-we-fact-check/',
 Outcome='Approved with caution',Caution_Note='No central public corrections log. UK focus, so of limited relevance.',
 Rationale='Full Fact is a current IFCN signatory with itemized funding, a published method, and a feedback and corrections policy. It lacks a public corrections log, the same shortfall that led to caution for AP and FactCheck.org. It is approved with caution for consistency and is unlikely to be used.'),
dict(Name='VERIFY (TEGNA)',Lean_Note='TEGNA broadcast group',
 IFCN_Status='In renewal (last accepted 2024-12-05; assessment pending)',IFCN_URL=IF+'verify',
 Corrections_Policy='Not located in our search',Corrections_Policy_URL='',
 Corrections_Log='Not located',Corrections_Log_URL='',
 Documented_Rating_Reversals='None located in our search.',Reversal_URLs='',
 Funding_Transparency='Partial: TEGNA newsroom-funded (qualitative)',Funding_URL='',
 Methodology='Partial (described in TEGNA materials)',Methodology_URL='https://www.tegna.com/tegna-expands-verify-to-stop-the-spread-of-disinformation-announces-appointment-of-managing-editor/',
 Outcome='Rejected',Caution_Note='No corrections policy located. Cited in catalog notes (#181) only.',
 Rationale='VERIFY is in IFCN renewal, but we could not locate a published corrections policy or corrections log. The about page redirected to a corporate brands page. Under identical criteria that is disqualifying until documented. This is not a finding of inaccuracy.'),
dict(Name='CNN Facts First / CNN fact checks',Lean_Note='CNN (Warner Bros. Discovery)',
 IFCN_Status='Never (not in IFCN signatory list)',IFCN_URL='https://ifcncodeofprinciples.poynter.org/signatories',
 Corrections_Policy='Not located for the fact-check unit (Facts First page returns 404)',Corrections_Policy_URL='',
 Corrections_Log='Not located',Corrections_Log_URL='',
 Documented_Rating_Reversals='Catalog case #18: CNN\'s Mar 4, 2025 fact-check of Trump\'s address initially called the "transgender mice" claim false and was walked back on Mar 5, 2025.',
 Reversal_URLs='https://www.cnn.com/2025/03/04/politics/fact-check-trump-address-congress',
 Funding_Transparency='No unit-level disclosure',Funding_URL='',
 Methodology='Not located',Methodology_URL='',
 Outcome='Rejected',Caution_Note='Never an IFCN signatory. No located methodology or corrections policy. Also a subject of several catalog cases.',
 Rationale='CNN\'s fact-check output has never been IFCN-verified, and we located no published fact-check methodology or corrections policy. Its record includes a documented walk-back of a Trump fact-check (#18). CNN is also a subject of many catalog cases.'),
dict(Name='PBS NewsHour fact checks',Lean_Note='Public broadcaster',
 IFCN_Status='Never (not in IFCN signatory list)',IFCN_URL='https://ifcncodeofprinciples.poynter.org/signatories',
 Corrections_Policy='Not located (standards page 404)',Corrections_Policy_URL='',Corrections_Log='Not located',Corrections_Log_URL='',
 Documented_Rating_Reversals='None located.',Reversal_URLs='',Funding_Transparency='Partial (public broadcaster)',Funding_URL='',Methodology='Not located',Methodology_URL='',
 Outcome='Rejected',Caution_Note='Cited only in catalog notes (#114).',
 Rationale='Not an IFCN signatory, and we could not locate a fact-check methodology or corrections page. Ineligible as independent confirmation under the identical criteria.'),
dict(Name='TWS Fact Check (Weekly Standard)',Lean_Note='Right-leaning (defunct 2018)',
 IFCN_Status='Lapsed (Expired Signatory); publication closed Dec 2018',IFCN_URL=IF+'tws-fact-check',
 Corrections_Policy='Not reachable (site defunct)',Corrections_Policy_URL='',Corrections_Log='Not reachable',Corrections_Log_URL='',
 Documented_Rating_Reversals='Not assessable.',Reversal_URLs='',Funding_Transparency='Not reachable',Funding_URL='',Methodology='Not reachable',Methodology_URL='',
 Outcome='Rejected',Caution_Note='Included for balance. Not cited in the catalog.',
 Rationale='A right-leaning former IFCN signatory. Its publication closed and its policies can no longer be verified, so it fails the documentation criteria on the same basis as VERIFY and The Dispatch.'),
]
nonfc=[
('Sharyl Attkisson (substack list "Media mistakes in reporting on Donald Trump")','Journalist compilation, not a fact-checker; cited as Truth/Primary source for about 21 cases','Not eligible: under the standard, journalists are never proof and cannot confirm. Use only as a lead to locate each outlet\'s own correction.'),
('iMediaEthics','Media-ethics news site that quotes outlet corrections','Not eligible as proof or confirmation. Acceptable only as a pointer to the outlet\'s own correction text, which must be located directly.'),
('Poynter (news articles / corrections roundups)','Journalism institute; parent of PolitiFact and IFCN','Not eligible as proof. Corrections roundups are pointers only.'),
('CAMERA','Advocacy organization','Not eligible.'),
('News outlets reporting on other outlets (AP, Reuters, NBC, CBS, NY Post, Fox News, Free Beacon, Daily Caller News Foundation, HuffPost, Business Insider, Newsweek, The Hill, KPIC/National Desk, Western Journal, Spiegel, BBC)','Journalism','Not eligible as proof. Only an outlet\'s OWN correction or retraction about its OWN story counts (admission against interest).'),
]
cols=['Name','Lean_Note','IFCN_Status','IFCN_URL','Corrections_Policy','Corrections_Policy_URL','Corrections_Log','Corrections_Log_URL','Documented_Rating_Reversals','Reversal_URLs','Funding_Transparency','Funding_URL','Methodology','Methodology_URL','Outcome','Caution_Note','Rationale']
with open('/workspace/reverify/factchecker-vetting.csv','w',newline='') as f:
    w=csv.DictWriter(f,fieldnames=cols); w.writeheader(); [w.writerow(r) for r in rows]
    for n,t,o in nonfc:
        w.writerow({'Name':n,'Lean_Note':t,'Outcome':'Not eligible (not a fact-checker)','Rationale':o})
json.dump({r['Name']:r['Outcome'] for r in rows},open('/workspace/reverify/vetting-outcomes.json','w'),indent=1)
md=['# Fact-checker vetting (Phase 1)','',f'Prepared Sep 24, 2026 (MT). IFCN status was pulled on Sep 24, 2026 from the public signatory data behind https://ifcncodeofprinciples.poynter.org/signatories (raw copy: `evidence/ifcn-signatories-api-2026-09-24.json`; extract: `evidence/ifcn-status-extract.json`). Every policy, funding, and methodology URL listed as present returned HTTP 200 from our box on Sep 24, 2026, except where noted (WaPo, AFP, Reuters and USA TODAY block or partly block curl; those were read via the web-fetch tool or search snapshot, as flagged).','',
'## Identical criteria applied to every checker','',
'1. **IFCN status**: current = pass; lapsed or in renewal = caution; never = caution. Status alone never approves or rejects.',
'2. **Published corrections policy**, located by us: required. If we cannot locate one, the outcome is **Rejected** (a documentation failure, not an accuracy finding).',
'3. **Public corrections log**: a missing log means caution.',
'4. **Documented rating corrections, reversals or retractions**, especially on Trump-related claims: open corrections are expected. A documented reversal of a politically salient rating, or an integrity failure, means caution.',
'5. **Funding transparency**: unitemized or unit-less disclosure means caution.',
'6. **Published methodology**: required. If none can be located, the outcome is Rejected.',
'7. **Operating status**: a defunct or leaderless unit is archive-only (caution) or Rejected if its policies can no longer be verified.','',
'Outcomes: **Approved** = passes 1-7 with no caution trigger. **Approved with caution** = passes 2 and 6 but hits one or more caution triggers. **Rejected** = fails 2 or 6. Under every outcome, a fact-checker is only ever cited as "Independently confirmed by <name>" after SwampForce has verified the case against the primary record. A checker is never the proof, and never confirms a case about its own parent outlet.','',
'Evidence was limited to documented items. "None located" means our search did not find one; it is not a claim that none exist.','',
'## Summary','','| Checker | Lean / owner | IFCN | Outcome |','|---|---|---|---|']
for r in rows: md.append(f"| {r['Name']} | {r['Lean_Note']} | {r['IFCN_Status']} | **{r['Outcome']}** |")
md+=['','Right-leaning checkers included for balance: Check Your Fact (Daily Caller), The Dispatch Fact Check, TWS Fact Check (Weekly Standard, defunct). The IFCN list shows no other US right-of-center signatory.','','## Detail','']
for r in rows:
    md+=[f"### {r['Name']}: {r['Outcome']}",'',f"- **Owner/lean:** {r['Lean_Note']}",f"- **IFCN:** {r['IFCN_Status']} ({r['IFCN_URL']})",
    f"- **Corrections policy:** {r['Corrections_Policy']} {r['Corrections_Policy_URL']}",f"- **Corrections log:** {r['Corrections_Log']} {r['Corrections_Log_URL']}",
    f"- **Documented corrections/reversals:** {r['Documented_Rating_Reversals']}",f"  - Links: {r['Reversal_URLs'] or 'n/a'}",
    f"- **Funding:** {r['Funding_Transparency']} {r['Funding_URL']}",f"- **Methodology:** {r['Methodology']} {r['Methodology_URL']}",
    f"- **Caution/condition:** {r['Caution_Note']}",'',f"**Rationale:** {r['Rationale']}",'']
md+=['## Sources cited in the catalog that are not fact-checkers','']
for n,t,o in nonfc: md.append(f"- **{n}** ({t}): {o}")
open('/workspace/reverify/factchecker-vetting.md','w').write('\n'.join(md)+'\n')
print('ok',len(rows))
