import csv
CL="https://www.courtlistener.com/docket/74823502/cable-news-network-inc-v-trump/"
TRO="https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.24.0.pdf"
cols=['Claim','Truth_Source_URL','Who_Pushed_It','Approximate_Duration','Deception_Form','Category_Tag','Item_ID','Notes','Evidence_Level','Primary_Source_URL','Proof_Basis','Correction_Visibility',
      'speaker','outlet','claim_date','exact_quote','claim_url','record_shows','evidence_level','proof_type','proof_url','related_catalog_items','dedupe_status']
rows=[
dict(
 Claim="That a federal judge “ordered President Donald Trump” to restore CNN, MS NOW and Politico’s White House press access.\nBegan: Sep 24, 2026 | Ended: No ending date (live as of Sep 24, 2026)",
 Truth_Source_URL=TRO,
 Who_Pushed_It="TIME (Callum Sutherland and Olivia-Anne Cleary)",
 Approximate_Duration="same day (live as of Sep 24, 2026)",
 Deception_Form="misstatement of court order (who was ordered)",
 Category_Tag="false / legal-record misstatement",
 Item_ID="NEW-2026-09-24-01",
 Notes="Temporary restraining order, ¶2: “Defendants (except for President Trump) and their agents, representatives, and all persons or entities acting in concert with them shall immediately return, reinstate, and restore the White House ‘hard pass’ press credentials…” The court expressly left the President out of the order. The substance of the story (the administration was ordered to restore access) is accurate; the error is naming Trump personally as the person ordered. Severity: low/technical, but the order's text directly contradicts it. ABC News (US) got it right: “The order requires the defendants, excluding President Donald Trump…” (https://abcnews.com/US/judge-orders-white-house-restore-press-passes-cnn/story?id=136709442). Same family of error as NEW-2026-09-24-02; merge them if you catalog this as one case.",
 Evidence_Level="Proven false", Primary_Source_URL=TRO, Proof_Basis="Official record",
 Correction_Visibility="Not corrected (as of Sep 24, 2026)",
 speaker="Callum Sutherland and Olivia-Anne Cleary", outlet="TIME", claim_date="2026-09-24",
 exact_quote="CNN, MS NOW, and Politico reporters were allowed back into the White House Thursday after a federal judge ordered President Donald Trump to immediately restore their press access.",
 claim_url="https://time.com/article/2026/09/24/judge-overturns-trump-white-house-media-ban-temporary-order-appeal/",
 record_shows="The TRO (ECF 24, Sep 24, 2026) orders “Defendants (except for President Trump)” and their agents to restore the hard passes. The President is expressly carved out.",
 evidence_level="Proven false", proof_type="Official record (court order)", proof_url=TRO,
 related_catalog_items="none (new category: press-access litigation)", dedupe_status="NEW. Not in term-split (250) or catalog-candidates.csv"),
dict(
 Claim="That a US judge “ordered Donald Trump” to restore White House access for CNN, Politico and MS NOW.\nBegan: Sep 24, 2026 | Ended: No ending date (live as of Sep 24, 2026)",
 Truth_Source_URL=TRO,
 Who_Pushed_It="ABC News (Australia), Rudi Maxwell with wires (Reuters/ABC)",
 Approximate_Duration="same day (live as of Sep 24, 2026)",
 Deception_Form="misstatement of court order (who was ordered), in the headline",
 Category_Tag="false / legal-record misstatement",
 Item_ID="NEW-2026-09-24-02",
 Notes="The headline reads “Judge orders Donald Trump to restore White House access to banned media organisations,” and the summary says “A US judge has ordered Donald Trump to restore access…” The order's operative paragraph excludes President Trump. The story is marked Reuters/ABC, but I could not verify whether Reuters' own copy uses the same wording, so this entry is attributed to ABC Australia only. Severity: low/technical. Merge with NEW-2026-09-24-01 if cataloged as one case.",
 Evidence_Level="Proven false", Primary_Source_URL=TRO, Proof_Basis="Official record",
 Correction_Visibility="Not corrected (as of Sep 24, 2026)",
 speaker="Rudi Maxwell (with wires)", outlet="ABC News (Australia)", claim_date="2026-09-24",
 exact_quote="A US judge has ordered Donald Trump to restore access to the White House for three media outlets he had banned: CNN, Politico and MS Now.",
 claim_url="https://www.abc.net.au/news/2026-09-24/us-judge-reverses-donald-trump-media-ban-cnn-politico-ms-now/107192236",
 record_shows="TRO ¶2 binds “Defendants (except for President Trump)” and their agents. It is not directed at Trump personally.",
 evidence_level="Proven false", proof_type="Official record (court order)", proof_url=TRO,
 related_catalog_items="none", dedupe_status="NEW"),
dict(
 Claim="That Trump “barred the Associated Press from the White House” in 2025 (Gulf of America dispute), presented as a precedent for the 2026 total ban on CNN, MS NOW and Politico.\nBegan: Sep 23, 2026 (this instance) | Ended: No ending date (live as of Sep 24, 2026)",
 Truth_Source_URL="https://storage.courtlistener.com/recap/gov.uscourts.dcd.277682/gov.uscourts.dcd.277682.46.0_1.pdf",
 Who_Pushed_It="NPR (David Folkenflik), syndicated by GPB (Morning Edition)",
 Approximate_Duration="live as of Sep 24, 2026",
 Deception_Form="overstatement / omitted context (scope of the AP restriction)",
 Category_Tag="misleading / missing context",
 Item_ID="NEW-2026-09-24-03",
 Notes="In AP v. Budowich (D.D.C., Apr. 8, 2025, ECF 46, p.9), Judge McFadden wrote: “The parties agree that no AP employee's hard pass has been revoked” (see also p.12: “both parties agreed that the AP's hard pass status had been unchanged”). The AP was kept out of the press pool, the Oval Office, Air Force One and many East Room events. It was not barred from the White House. The 2026 ban is different: it revoked hard passes and blocked access to the whole complex. Saying the AP was “barred from the White House” leaves out that the AP kept its hard passes and general access to the press facilities, which makes the 2025 action look like the 2026 one. Labeled misleading rather than false because “barred” is partly true for specific events. I found no fact-check on this line.",
 Evidence_Level="Rated misleading", Primary_Source_URL="https://storage.courtlistener.com/recap/gov.uscourts.dcd.277682/gov.uscourts.dcd.277682.46.0_1.pdf", Proof_Basis="Official record",
 Correction_Visibility="Not corrected (as of Sep 24, 2026)",
 speaker="David Folkenflik", outlet="NPR (via GPB)", claim_date="2026-09-23",
 exact_quote="Trump barred the Associated Press from the White House last year, after he deemed the Gulf of Mexico should be called the Gulf of America, but the news wire declined to follow suit.",
 claim_url="https://www.gpb.org/news/2026/09/23/major-news-outlets-banned-by-trump-will-have-their-day-in-court",
 record_shows="The court record in AP v. Budowich says no AP hard pass was revoked. The restriction covered the pool, the Oval Office, Air Force One and many limited-access events, not the White House itself.",
 evidence_level="Rated misleading", proof_type="Official record (court opinion; key fact omitted)", proof_url="https://storage.courtlistener.com/recap/gov.uscourts.dcd.277682/gov.uscourts.dcd.277682.46.0_1.pdf",
 related_catalog_items="none", dedupe_status="NEW. No AP-access case in the catalog"),
]
with open('candidates.csv','w',newline='',encoding='utf-8') as f:
    w=csv.DictWriter(f,fieldnames=cols,quoting=csv.QUOTE_ALL); w.writeheader(); [w.writerow(r) for r in rows]

wcols=['watch_id','claim_or_framing','speaker','outlet','date','exact_quote','claim_url','status','what_record_shows','record_urls','evidence_that_would_settle_it','related_catalog_items']
W=[
('W-01','Trump called his own action a “ban on the free press” (an admission)','Jacqui Heinrich / WHCA; also NBC News; The Guardian live blog; plaintiffs\' complaint ¶38','WHCA; NBC; Guardian; Complaint (ECF 1)','2026-09-18 to 2026-09-24',
 'WHCA: “The president said it plainly in the Oval Office, describing his own planned action as a ‘ban on the free press.’” Guardian: “the president seemed to admit that what he is attempting to do is a violation of the freedom of the press”',
 'https://whca.press/2026/09/18/statement-on-white-house-position-on-cnn-msnow-and-politico/',
 'Accurate quote; the characterization is contested',
 'Transcript: after the reporter asked “What do you envision the ban to look like, sir?”, and after Trump had asked “which ban?”, he said “Oh, the ban on the free press, right? Uh, a very simple ban. I don\'t want them in my office. I don\'t want them here.” The words are his and were not put to him in the question. Whether he meant it sarcastically (mocking critics) or as an admission is interpretation. The quote is not false.',
 'https://rollcall.com/factbase/trump/transcript/donald-trump-remarks-healthcare-drug-prices-oval-office-september-18-2026/ ; https://www.whitehouse.gov/videos/president-trump-makes-an-announcement-on-healthcare-sep-18-2026/',
 'Review the tone in the unedited White House/C-SPAN video (at about 00:53:38 in the Factba.se timing), or a clarification from Trump or the White House. Headlines that drop the question and the “which ban?” exchange would count as an omission.','#32, #221 (context-stripped quote pattern)'),
('W-02','“Donald Trump just did what dictators throughout history have done”','Sen. Chuck Schumer','X post, quoted by CNN, NYT/Inquirer, Guardian','2026-09-18',
 '“Donald Trump just did what dictators throughout history have done. This is a democracy. You will not be able to manipulate the news or hide the truth.”',
 'https://www.cnn.com/2026/09/18/media/trump-claims-ban-cnn-msnow-politico-white-house',
 'Opinion / characterization',
 'The facts underneath are documented: Trump announced the ban and cited “FAKE NEWS” and “purposely negative” stories. Context often left out: a federal court restored the passes within 6 days, the White House said it began complying the same morning (Stopperich decl.), and the White House filed a notice-and-response letter process (the court found it inadequate). Calling someone a dictator is opinion.',
 CL,'Not settleable as fact. It becomes a candidate only if it is paired with a factual misstatement (for example, claiming reporters were arrested or the outlets were shut down).','#32, #221 (older “dictator” framing)'),
('W-03','“We will not accept authoritarianism” / the ban as an authoritarian crackdown','Sen. Bernie Sanders; Democratic lawmakers (CNN summary)','X posts via NYT/Inquirer; CNN','2026-09-18 to 2026-09-19',
 'Sanders: “We will not allow Trump to undermine the First Amendment, the Constitution, and our democracy… We will not accept authoritarianism.”',
 'https://www.inquirer.com/news/nation-world/trump-media-ban-cnn-msnow-politico-white-house-reaction-news-outlets-politicians-20260919.html',
 'Opinion','Characterization. No checkable factual claim in the quote.',CL,'Not settleable as fact.','#32, #221'),
('W-04','The White House “defied” or “flouted” the court order on Sep 24','Axios headline (original, later changed); Forbes URL slug; Guardian (“initially seemed to flout”); plaintiffs (“repeatedly violated”)','Axios; Forbes; Guardian; plaintiffs\' filing ECF 25/26','2026-09-24',
 'Guardian: “The outlets had requested an emergency hearing after the White House initially seemed to flout a judge\'s order”. Axios\' original headline “White House defies court order, doesn\'t reinstate access for banned reporters” appears only in search indexes. The live page now reads “White House reinstates access for banned reporters,” so I could not verify the original wording on the live page.',
 'https://www.theguardian.com/us-news/2026/sep/24/judge-orders-trump-restore-white-house-access-cnn-ms-now-politico-media-ban',
 'Contested',
 'Sworn declaration of Micah Stopperich (ECF 27/28): WH Operations notified at 7:10 a.m. ET (5:10 MT) to restore access; reinstating began at 7:25 ET; Secret Service said badges were “back on” at 9:07 ET (7:07 MT); confiscated badges were at the entry gate around 9:55 ET (7:55 MT). The outlets say reporters were turned away into the 11 a.m. ET hour (TheWrap) and were back in around noon ET (10 a.m. MT). Reuters quoted MS NOW\'s Barrón-López saying it was unclear whether this was defiance or an entry-system problem. After the filing, the judge denied the emergency hearing (NBC). CNN\'s Klein was first turned away around 6 a.m. ET, before the 7:10 notice. The TRO was issued shortly after midnight ET.',
 'https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.27.0.pdf ; https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.26.0.pdf ; https://www.nbcnews.com/politics/trump-administration/judge-ruling-white-house-restore-access-media-ban-cnn-politico-ms-now-rcna599391',
 'Secret Service gate logs; any court finding on compliance, contempt or show-cause order; the White House account of the 6–7 a.m. ET gap.','none'),
('W-05','Secret Service confiscated passes on Sep 24 from journalists “whose hard passes had not previously been confiscated” / “some having their badges taken for the first time”','TIME; The Guardian (Jeremy Barr)','TIME; Guardian','2026-09-24',
 'TIME quoting ECF 25: “Secret Service agents confiscated the hard pass of journalists whose hard passes had not previously been confiscated”. Guardian: “with some having their badges taken for the first time.”',
 'https://time.com/article/2026/09/24/judge-overturns-trump-white-house-media-ban-temporary-order-appeal/',
 'Contested / superseded wording',
 'The plaintiffs filed a CORRECTED notice (ECF 26) that removed the “whose hard passes had not previously been confiscated” clause and changed “agents” to “A Secret Service agent confiscated the hard pass of journalists from all three organizations.” Both outlets quote or paraphrase the superseded version. The corrected filing still alleges confiscations that morning. The Stopperich declaration does not address them.',
 'https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.25.0.pdf ; https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.26.0.pdf',
 'The plaintiffs explaining why they corrected ECF 25; Secret Service records of badge seizures on Sep 24.','none'),
('W-06','The judge “overturned,” “reversed,” or “blocked” the ban, or “halted enforcement of the ban for 14 days”','BBC; Reuters (via ABC Australia/ThePrint); TIME and ABC AU URL slugs; Forbes','BBC; Reuters; ABC AU; TIME','2026-09-24',
 'BBC: “He ordered the immediate return of the outlets\' press passes and a halt to enforcement of the ban for 14 days.” Reuters: “Kelly\'s overnight ruling blocked the ban for 14 days.”',
 'https://www.bbc.com/news/articles/cqe8ek7608mlo',
 'Contested (scope of relief)',
 'The operative paragraph of the TRO orders only the return and reinstatement of the hard passes revoked on or about Sep 18. It excludes the President, lasts 14 days, and rests only on Fifth Amendment due process. The First Amendment claims were not reached. The order says nothing about Oval Office or pool access; reporters were not allowed into the Oval Office spray with Xi on Sep 24. The motion it “GRANTED” did ask for a broader restraint on implementing the ban, so whether the order reaches beyond the hard passes is unclear.',
 TRO,'A court clarification or the preliminary-injunction ruling on scope, especially Oval Office and pool access.','none'),
('W-07','DOJ said the convention story threatened national security (BBC juxtaposition)','Grace Eliza Goodwin','BBC','2026-09-24',
 '“the US Department of Justice had accused the news outlets of threatening national security with their coverage. Government lawyers cited stories about missile stockpiles, the construction of the White House ballroom and the recent Republican midterm convention.”',
 'https://www.bbc.com/news/articles/cqe8ek7608mlo',
 'Possible misleading juxtaposition (not rated)',
 'The Sep 22 Politico letter lists incidents that “threatened national security and/or spread falsehoods.” The convention item is rebutted with viewership numbers, which makes it a falsity complaint, not a security one. The ballroom item is described as a Secret Service security-details disclosure. BBC\'s wording can be read as saying the convention story was cited as a security threat. The letters themselves lump both categories together (the judge noted this ambiguity).',
 'https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.16.3_1.pdf',
 'A BBC clarification, or DOJ stating which items were security claims and which were falsity claims.','none'),
('W-08','The Guardian: Trump “falsely claimed” the BBC “used technology to put words in his mouth”; “They put horrible fighting words into my mouth,” Trump claimed, “incorrectly”','Robert Mackey et al. (live blog)','The Guardian','2026-09-18',
 '“…and, not for the first time, falsely claimed that the BBC documentary on the January 6 2021 Capitol riot he has sued the corporation over used technology to put words in his mouth that he never actually said. ‘They put horrible fighting words into my mouth,’ Trump claimed, incorrectly.”',
 'https://www.theguardian.com/us-news/live/2026/sep/18/us-politics-midterms-early-voting-cost-of-living-iran-war-trump-kennedy-center-institute-of-peace-latest-news-updates?page=with%3Ablock-6aada5b88f08c4af80ed7693',
 'Contested. Initially looked like a candidate; downgraded',
 'In the Sep 18 transcript Trump does not mention technology or AI. He says the BBC “changed my language and they put words in my mouth.” The BBC\'s own Nov 13, 2025 correction admits the Panorama splice “gave the mistaken impression that President Trump had made a direct call for violent action,” and the Guardian does not mention that. However, Trump DID claim in April 2026 (60 Minutes) that the BBC used AI, which the BBC denies, so “not for the first time” has a basis. The spliced words were his own, so “put words in my mouth” is literally loose. Omission of the BBC admission: yes. Demonstrably false: no. Also, Panorama (“Trump: A Second Chance?”) was not a documentary “on the January 6 riot.”',
 'https://rollcall.com/factbase/trump/transcript/donald-trump-remarks-healthcare-drug-prices-oval-office-september-18-2026/ ; https://www.bbc.com/news/articles/c874nw4g2zzo ; https://deadline.com/2026/04/donald-trump-claims-bbc-used-ai-edit-jan-6-capitol-speech-1236873435/',
 'A fact-check rating on Trump\'s Sep 18 BBC statement, or a Guardian clarification. If a fact-checker rated the Guardian\'s framing misleading for omitting the BBC admission, it could be promoted.','#58 (BBC Panorama splice)'),
('W-09','The ban was motivated by critical coverage vs. the administration\'s national-security rationale','Plaintiffs; press-freedom groups; many outlets vs. White House/DOJ','various','2026-09-18 to 2026-09-24',
 'Plaintiffs: the ban was imposed “for one simple reason: He dislikes the content of their coverage.” DOJ/WH letters: the outlets trafficked “in verifiable falsehoods about national security… and publishing sensitive or classified information.”',
 'https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.1.0.pdf',
 'Contested (to be decided in the preliminary-injunction phase)',
 'Trump\'s own Sep 18 words focus on “fake news” and “purposely negative stories.” The national-security rationale first appears in writing in the Sep 22 letters. The judge (TRO p.6) found “nothing in the record that predates this suit suggests” a national-security motive, but reserved the First Amendment retaliation question. The letters name specific stories (the East Wing bunker, interceptor depletion, ballroom security funding).',
 TRO+' ; https://storage.courtlistener.com/recap/gov.uscourts.dcd.296754/gov.uscourts.dcd.296754.16.1_1.pdf',
 'The preliminary-injunction ruling on the First Amendment claim; any classified or unclassified declaration linking the named stories to actual harm.','none'),
('W-10','Trump: “Sometimes you need a dictator” (Davos, Jan 21, 2026), cited in the current “dictator” framing','Trump (quoted); recirculated in commentary','Snopes (fact-check: genuine)','2026-01-21 (recirculating)',
 '“Usually they say, ‘He\'s a horrible dictator-type person. I\'m a dictator.’ But sometimes you need a dictator. But they didn\'t say that in this case.”',
 'https://www.snopes.com/fact-check/trump-sometimes-you-need-a-dictator/',
 'Genuine quote; the framing is contested',
 'Snopes confirms Trump said it, right after referring to critics calling him a dictator, and followed it with “it\'s common sense.” Whether it was a joke or sincere is interpretation. Any use that drops the lead-in (“Usually they say…”) is a context omission. Older related catalog cases are about “dictator on day one” context stripping.',
 'https://www.snopes.com/fact-check/trump-sometimes-you-need-a-dictator/',
 'The full video (White House YouTube FnhWsFMAqO4, per Snopes). A specific outlet presenting it without the lead-in would be a candidate.','#32, #221'),
('W-11','Trump\'s UN speech “raises authoritarianism concerns”','Lenox Washington','The Source','2026-09-23',
 '“His warnings to Iran and Cuba, alongside attacks on international institutions, echoed the language critics have identified as authoritarian in his broader political rhetoric.”',
 'https://thesource.com/2026/09/23/trumps-un-speech-raises-authoritarianism-concerns-with-threats-against-iran-and-cuba/',
 'Opinion',
 'The quoted speech lines (“annihilate the Islamic Republic”, “drive them into hell”, the ICC criticism) match the UN News summary. The “authoritarian” label is commentary.',
 'https://news.un.org/en/story/2026/09/1168397',
 'Not settleable as fact. Check against the full UN transcript if a specific misquote is alleged.','#32, #221'),
]
with open('watchlist.csv','w',newline='',encoding='utf-8') as f:
    w=csv.writer(f,quoting=csv.QUOTE_ALL); w.writerow(wcols); [w.writerow(r) for r in W]
print(len(rows),len(W))
