import csv,json,collections
P='primary'; L='lead (reported, not confirmed by primary record)'; C='congressional record'; LAW='law/court'
S=[
# id,title,type,publisher,date,url,supports,class
("crowds-site","Crowds on Demand website (own marketing)","company statement","Crowds on Demand","accessed 2026-09-24","https://crowdsondemand.com/","Company openly sells hired crowds/protests/rallies",P),
("bakala-order","Bakala v. Krupa, D.S.C. No. 9:18-cv-02590, Order (ECF 210)","court record","U.S. District Court, D.S.C. (via CourtListener RECAP)","2021-09-20","https://storage.courtlistener.com/recap/gov.uscourts.scd.245575/gov.uscourts.scd.245575.210.0.pdf","Court describes Crowds on Demand paid-actor protests at plaintiff's home; CoD/Swart settled",P),
("nola-council","New Orleans City Council 2019-03-14 meeting page (Resolution R-19-78, Entergy $5M penalty)","official record","New Orleans City Council","2019-03-14","https://council.nola.gov/meetings/2019/20190314-regular-meeting/","Council fined Entergy $5M over paid actors at 2017-2018 hearings",P),
("entergy-stmt","Entergy Completes Internal Investigation Regarding New Orleans Power Station Advocacy","company statement","Entergy Corp.","2018","https://www.entergy.com/news/entergy-completes-internal-investigation-regarding-new-orleans-power-station-advocacy","Entergy confirms subcontractor (Crowds on Demand via Hawthorn Group) paid people to attend/speak",P),
("fec-trump-2015","FEC committee page, Donald J. Trump for President (C00580100); 2015 YE report, $12,000 to Gotham Government Relations 10/08/2015 'EVENT CONSULTING' (image 201601319005280481)","FEC filing","Federal Election Commission","2016-01-31","https://www.fec.gov/data/committee/C00580100/","Payment to firm reported to have recruited paid extras for June 2015 announcement (payment documented; purpose reported)",P),
("thr-2015","Hollywood Reporter: Trump campaign offered actors $50 to cheer (2015)","news","Hollywood Reporter","2015-06-17","https://www.hollywoodreporter.com/news/politics-news/donald-trump-campaign-offered-actors-803161/","Casting-agency email re paid extras at Trump announcement",L),
("ira-indictment","United States v. Internet Research Agency LLC et al., Indictment (D.D.C. 1:18-cr-32)","DOJ charging document","U.S. Department of Justice","2018-02-16","http://web.archive.org/web/20251231210723/https://www.justice.gov/d9/fieldable-panel-panes/basic-panes/attachments/2018/02/16/internet_research_agency_indictment.pdf","Russian IRA allegedly paid Americans to stage 2016 rally stunts (charges; not adjudicated; Concord entities dismissed 2020)",P),
("ssci-vol2","Senate Select Committee on Intelligence, Report Vol. 2: Russia's Use of Social Media (bipartisan; Republican chair Burr)","congressional report","U.S. Senate SSCI","2019-10-08","https://www.intelligence.senate.gov/sites/default/files/documents/Report_Volume2.pdf","IRA organized real-world rallies in the U.S.",C),
("osf-protest-stmt","The Open Society Foundations and Protest in the United States","official statement","Open Society Foundations","accessed 2026-09-24","https://www.opensocietyfoundations.org/newsroom/the-open-society-foundations-and-protest-in-the-united-states","OSF says it does not pay people to protest or coordinate protesters",P),
("osf-db","Open Society Foundations awarded-grants database","foundation grant database","Open Society Foundations","accessed 2026-09","https://www.opensocietyfoundations.org/grants/past","Grant IDs, amounts, years, purposes (see money-flows.csv rows)",P),
("nokings","No Kings official site","organizer statement","No Kings coalition (Indivisible et al.)","accessed 2026-09-24","https://www.nokings.org/","Organizer; nonviolence statement; Oct 17 2026 'Vote Early' event",P),
("factcheck-craigslist","Online Posts Make Baseless Claim Linking Protesters to Craigslist Ad","fact-check","FactCheck.org","2025-06","https://www.factcheck.org/2025/06/online-posts-make-baseless-claim-linking-protesters-to-craigslist-ad/","June 2025 LA 'paid protester' Craigslist ad was a hoax/prank",L),
("snopes-osf-nokings","Snopes: claims Soros funded No Kings (Oct 2025 / Apr 2026)","fact-check","Snopes","2026-04-03","https://www.snopes.com/news/2026/04/03/no-kings-funding-soros-singham/","No evidence OSF directly funded No Kings; OSF 2025 grants not yet public",L),
("nyt-singham","A Global Web of Chinese Propaganda Leads to a U.S. Tech Mogul","news","New York Times","2023-08-05","http://web.archive.org/web/20260111052424/https://www.nytimes.com/2023/08/05/world/europe/neville-roy-singham-china-propaganda.html","Reports Singham funding of People's Forum, Code Pink, Tricontinental etc. via DAFs/foundations",L),
("rubio-letter","Rubio probes funding for organizations that promote CCP agenda in the U.S. (letter to AG Garland, Wayback capture)","congressional letter","Sen. Marco Rubio (R)","2023-08-09","http://web.archive.org/web/20230812233957/https://www.rubio.senate.gov/rubio-probes-funding-for-organizations-that-promote-ccp-agenda-in-the-u-s/","Request for FARA review of Singham-linked entities (request, not finding)",C),
("wm-2025-09-04","Chairman Smith exposes U.S. nonprofit as likely CCP-funded propaganda arm (letter to People's Forum)","congressional letter","House Ways and Means Committee (Republican majority)","2025-09-04","https://waysandmeans.house.gov/2025/09/04/chairman-smith-exposes-u-s-nonprofit-as-likely-ccp-funded-propaganda-arm-operating-under-tax-exempt-status/","Majority allegations re People's Forum; quotes People's Forum 2021 acknowledgment of Singham support",C),
("wm-2025-10-06","Ways and Means letter to IRS re Singham network (PDF)","congressional letter","House Ways and Means Committee (Republican majority)","2025-10-06","https://waysandmeans.house.gov/wp-content/uploads/2025/10/10.6.25-Letter-to-IRS.pdf","Request that IRS examine tax-exempt status (request, not finding)",C),
("wm-2026-07-24","Chairman Smith issues subpoenas to CCP-linked Singham network nonprofits","congressional press release","House Ways and Means Committee (Republican majority)","2026-07-24","https://waysandmeans.house.gov/2026/07/24/icymi-chairman-smith-issues-subpoenas-to-ccp-linked-singham-network-nonprofits-after-their-refusal-to-comply-with-committee-oversight/","Subpoenas to People's Forum, BreakThrough News, Tricontinental",C),
("fox-sdny","Fox News: federal grand jury probe of Singham network (citing sources)","news","Fox News","2026-06-29","https://www.foxnews.com/politics/doj-launches-grand-jury-probe-marxist-mogul-neville-roy-singhams-funding-leftist-groups","Reported SDNY grand jury activity; no charges",L),
("dni-iran","Statement from DNI Avril Haines on Recent Iranian Influence Efforts (Wayback capture)","official statement","Office of the Director of National Intelligence","2024-07-09","http://web.archive.org/web/20240715231842/https://www.dni.gov/index.php/newsroom/press-releases/press-releases-2024/3842-statement-from-director-of-national-intelligence-avril-haines-on-recent-iranian-influence-efforts","Iranian government actors posed as activists online, encouraged Gaza protests, some financial support to protesters (no recipients/amounts named)",P),
("ed-117","U.S. Dept. of Education releases latest Section 117 foreign funding disclosures (Wayback capture)","official statement","U.S. Department of Education","2026-02-11","http://web.archive.org/web/20260904064207/https://www.ed.gov/about/news/press-release/us-department-of-education-releases-latest-foreign-funding-disclosures-federally-funded-american-universities","Qatar largest 2025 foreign source to universities (>$1.1B); gifts to universities, not protest groups",P),
("hawley-invest","Hawley launches investigation into organizations bankrolling LA riots","congressional press release","Sen. Josh Hawley (R)","2025-06-11","https://www.hawley.senate.gov/hawley-launches-investigation-into-organizations-bankrolling-la-riots/","Letters to CHIRLA, Union del Barrio, PSL (allegations/requests)",C),
("hawley-chirla","Hawley letter to CHIRLA (PDF)","congressional letter","Sen. Josh Hawley (R)","2025-06-11","https://www.hawley.senate.gov/wp-content/uploads/2025/06/Hawley-Letter-to-Coalition-for-Humane-Immigrant-Rights.pdf","Request for records",C),
("hjc-chirla","Jordan, McClintock, Biggs letter to CHIRLA (PDF)","congressional letter","House Judiciary Committee (Republican majority)","2025-06-24","https://judiciary.house.gov/sites/evo-subsites/republicans-judiciary.house.gov/files/evo-media-document/2025-06-24-jdj-tm-ab-to-salas-re-la-riots.pdf","Inquiry citing ~$1M federal grants to CHIRLA; no finding of misuse",C),
("hsgac-bruner","Testimony of Seamus Bruner (Government Accountability Institute), Senate HSGAC hearing","congressional hearing testimony (witness is think tank)","U.S. Senate HSGAC (Republican majority)","2026-02","https://www.hsgac.senate.gov/wp-content/uploads/Seamus-Bruner-Testimony.pdf","Witness allegations on NGO funding (lead only)",L),
("nspm7","NSPM-7: Countering Domestic Terrorism and Organized Political Violence","executive order/memorandum","The White House","2025-09-25","https://www.whitehouse.gov/presidential-actions/2025/09/countering-domestic-terrorism-and-organized-political-violence/","Directs JTTF/Treasury/IRS to investigate funders of political violence",P),
("nspm7-fr","NSPM-7 (Federal Register 2025-19141)","Federal Register","Office of the Federal Register","2025-09-30","https://www.federalregister.gov/documents/2025/09/30/2025-19141/countering-domestic-terrorism-and-organized-political-violence","Same, official publication",P),
("schumer-1016","Leader Schumer Floor Remarks Supporting Americans' Fundamental Rights to Free Speech and Peaceful Protest","official statement","Senate Democratic Caucus","2025-10-16","https://www.democrats.senate.gov/news/press-releases/leader-schumer-floor-remarks-supporting-americans-fundamental-rights-to-free-speech-and-peaceful-protest","Senate Democratic leader promoted No Kings (Oct 18, 2025)",P),
("johnson-1017","Speaker Johnson remarks on 'Hate America rally'","official statement","Speaker Mike Johnson (R)","2025-10-17","https://mikejohnson.house.gov/news/documentsingle.aspx?DocumentID=2733","Speaker criticized No Kings",P),
("gao-b326944","GAO B-326944, EPA—Application of Publicity or Propaganda and Anti-Lobbying Provisions","GAO decision","U.S. Government Accountability Office","2015-12-14","http://web.archive.org/web/20240105222759/https://www.gao.gov/products/b-326944","Example of GAO finding an agency itself violated anti-lobbying/propaganda riders",P),
("usasp-chirla-24","USASpending: DHS/USCIS Citizenship & Integration grant to CHIRLA (23CICET00327)","federal award record","USASpending.gov","FY2024","https://www.usaspending.gov/award/ASST_NON_23CICET00327_070","$450K citizenship-education grant",P),
("usasp-chirla-23","USASpending: USCIS grant to CHIRLA (22CICET00277)","federal award record","USASpending.gov","FY2023","https://www.usaspending.gov/award/ASST_NON_22CICET00277_070","$250K citizenship-education grant",P),
("usasp-chirla-22","USASpending: USCIS grant to CHIRLA (21CICET00204)","federal award record","USASpending.gov","FY2022","https://www.usaspending.gov/award/ASST_NON_21CICET00204_070","$250K citizenship-education grant",P),
("usasp-search","USASpending.gov award search (recipient searches run 2026-09)","federal award database","USASpending.gov","accessed 2026-09","https://www.usaspending.gov/search","No federal awards found to main protest organizers (see raw/usa/)",P),
("fec-bulk","FEC bulk data (individual contributions, committee-to-committee, operating expenditures)","FEC data","Federal Election Commission","accessed 2026-09","https://www.fec.gov/data/browse-data/?tab=bulk-data","Contribution totals in money-flows.csv",P),
("lda-api","Lobbying Disclosure Act filings (LD-1/LD-2) via lda.gov","LDA data","U.S. Senate / House (lda.gov)","accessed 2026-09","https://lda.gov/","Lobbying totals",P),
("pp-explorer","ProPublica Nonprofit Explorer (mirror of IRS Form 990 e-file data)","IRS filing mirror","ProPublica / IRS","accessed 2026-09","https://projects.propublica.org/nonprofits/","990 revenue, Schedule I grants (per-filing links in money-flows.csv/orgs.csv)",P),
("irs-teos","IRS Tax Exempt Organization Search","IRS database","Internal Revenue Service","accessed 2026-09","https://apps.irs.gov/app/eos/","Exempt status, e-filed returns (site returns 403 to automated checks; loads in a browser)",P),
("irs-disclosure","IRS: Public Disclosure and Availability of Exempt Organizations Returns and Applications","IRS guidance","Internal Revenue Service","current","https://www.irs.gov/charities-non-profits/public-disclosure-and-availability-of-exempt-organizations-returns-and-applications-documents-subject-to-public-disclosure","Donor names/addresses on Schedule B not public for most exempt orgs",P),
("irs-schb","IRS Schedule B (Form 990) and instructions","IRS form","Internal Revenue Service","current","https://www.irs.gov/forms-pubs/about-schedule-b-form-990-990-ez-or-990-pf","Contributor reporting rules",P),
("td9898","T.D. 9898: Returns by Exempt Organizations and Returns Filed by Political Organizations (Schedule B donor names no longer required for most non-501(c)(3)s)","final regulation","Treasury/IRS, Federal Register","2020-05-28","https://www.federalregister.gov/documents/2020/05/28/2020-11324/returns-by-exempt-organizations-and-returns-by-certain-non-exempt-organizations","2020 rule removing donor names from Schedule B for 501(c)(4) etc.",LAW),
("usc-6104","26 U.S.C. 6104 (publicity of information)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/26/6104","Contributor names exempt from public disclosure (except private foundations/527s)",LAW),
("usc-6033","26 U.S.C. 6033 (returns by exempt organizations)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/26/6033","Filing requirements",LAW),
("cfr-501c4","26 C.F.R. 1.501(c)(4)-1 (social welfare organizations)","regulation","Cornell LII","current","https://www.law.cornell.edu/cfr/text/26/1.501(c)(4)-1","Primary-purpose test; political activity not primary",LAW),
("usc-1352","31 U.S.C. 1352 (Byrd Amendment)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/31/1352","Bars appropriated funds for lobbying to influence federal awards",LAW),
("usc-1913","18 U.S.C. 1913 (lobbying with appropriated moneys)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/18/1913","Bars appropriated funds for grassroots lobbying of Congress",LAW),
("cfr-200450","2 C.F.R. 200.450 (lobbying costs unallowable)","regulation","Cornell LII","current","https://www.law.cornell.edu/cfr/text/2/200.450","Federal grant funds cannot pay for lobbying/electioneering",LAW),
("usc-1601","2 U.S.C. 1601 et seq. (Lobbying Disclosure Act)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/2/chapter-26","Lobbying registration/reporting",LAW),
("usc-207","18 U.S.C. 207 (post-employment restrictions)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/18/207","Revolving-door cooling-off periods (1 yr House, 2 yr Senate members)",LAW),
("usc-611","22 U.S.C. 611 et seq. (FARA)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/22/chapter-11/subchapter-II","Foreign agent registration",LAW),
("usc-30121","52 U.S.C. 30121 (contributions by foreign nationals)","statute","Cornell LII","current","https://www.law.cornell.edu/uscode/text/52/30121","Foreign nationals barred from election spending",LAW),
("fara-efile","FARA eFile public search","FARA database","U.S. Department of Justice","accessed 2026-09","https://efile.fara.gov/ords/fara/f?p=1235:10","Where FARA registrations can be searched (not queried in this pass)",P),
("first-amend","First Amendment (Constitution Annotated)","constitution","Library of Congress","current","https://constitution.congress.gov/constitution/amendment-1/","Assembly and petition rights",LAW),
("naacp-alabama","NAACP v. Alabama ex rel. Patterson, 357 U.S. 449 (1958)","Supreme Court opinion","Justia","1958-06-30","https://supreme.justia.com/cases/federal/us/357/449/","Donor/member privacy protected by First Amendment",LAW),
("citizens-united","Citizens United v. FEC, 558 U.S. 310 (2010)","Supreme Court opinion","Justia (U.S. Reports)","2010-01-21","https://supreme.justia.com/cases/federal/us/558/310/","Corporations/unions may make independent expenditures",LAW),
("afp-bonta","Americans for Prosperity Foundation v. Bonta, 594 U.S. 595 (2021)","Supreme Court opinion","Supreme Court of the United States","2021-07-01","https://www.supremecourt.gov/opinions/20pdf/19-251_p86b.pdf","Struck California's blanket donor-disclosure demand",LAW),
("house-rc-2010-391","House Roll Call 391 (111th, 2010): DISCLOSE Act H.R. 5175 passage","roll call","Clerk of the House","2010-06-24","https://clerk.house.gov/Votes/2010391","Passed 219-206",P),
("sen-2010-220","Senate Vote 220 (111th Cong., 2nd sess.): cloture on DISCLOSE Act","roll call","U.S. Senate","2010-07-27","https://www.senate.gov/legislative/LIS/roll_call_votes/vote1112/vote_111_2_00220.htm","Failed 57-41",P),
("sen-2010-240","Senate Vote 240 (111th Cong., 2nd sess.): cloture on DISCLOSE Act","roll call","U.S. Senate","2010-09-23","https://www.senate.gov/legislative/LIS/roll_call_votes/vote1112/vote_111_2_00240.htm","Failed 59-39",P),
("sen-2012-179","Senate Vote 179 (112th Cong., 2nd sess.): cloture on DISCLOSE Act of 2012","roll call","U.S. Senate","2012-07-16","https://www.senate.gov/legislative/LIS/roll_call_votes/vote1122/vote_112_2_00179.htm","Failed 51-44",P),
("sen-2012-180","Senate Vote 180 (112th Cong., 2nd sess.): cloture on DISCLOSE Act of 2012","roll call","U.S. Senate","2012-07-17","https://www.senate.gov/legislative/LIS/roll_call_votes/vote1122/vote_112_2_00180.htm","Failed 53-45",P),
("sen-2022-346","Senate Vote 346 (117th Cong., 2nd sess.): cloture on S.4822 DISCLOSE Act of 2022","roll call","U.S. Senate","2022-09-22","https://www.senate.gov/legislative/LIS/roll_call_votes/vote1172/vote_117_2_00346.htm","Failed 49-49",P),
("house-rc-2024-477","House Roll Call 477 (118th, 2024): H.R. 9495 passage","roll call","Clerk of the House","2024-11-21","https://clerk.house.gov/Votes/2024477","Passed 219-184; not enacted",P),
("hr3554","H.R. 3554 (119th) Close the Revolving Door Act of 2025 (bill text, GovInfo)","bill","GovInfo","2025-05-21","https://www.govinfo.gov/app/details/BILLS-119hr3554ih","Lifetime lobbying ban for ex-members; in committee",P),
("s2376","S. 2376 (119th) Stop FUNDERs Act (bill text, GovInfo)","bill","GovInfo","2025-07-22","https://www.govinfo.gov/app/details/BILLS-119s2376is","Would add riot-related offenses to RICO; in committee",P),
("politifact-mn","PolitiFact: Critics of Minnesota anti-ICE protests falsely call protesters paid","fact-check","PolitiFact","2026-01-26","https://www.politifact.com/factchecks/2026/jan/26/donald-trump/trump-paid-protesters-ice-minnesota-minneapolis/","Claim rated unsupported",L),
("snopes-300m","Billionaires support groups behind 'No Kings,' but they didn't spend $300M to fund protests","fact-check","Snopes","2025-10","https://www.snopes.com/fact-check/billionaires-no-kings-protests/","$300M claim misrepresents grants to participating orgs",L),
("newsnation-swart","Publicity firm offered $20 million to recruit demonstrators for anti-Trump protests (Swart interview)","news","NewsNation","2025-07","https://www.newsnationnow.com/politics/publicity-firm-20-million-trump-protests/","Swart says he declined ~$20M offer for Good Trouble Lives On; client not named",L),
("seid-gift","ProPublica/NYT: Barre Seid $1.6B transfer to Marble Freedom Trust","news","ProPublica","2022-08-22","https://www.propublica.org/article/dark-money-leonard-leo-barre-seid","Ultimate donor behind Marble (not in public filing)",L),
]
rows=[dict(zip(['id','title','type','publisher_or_agency','date','url','supports','classification'],s)) for s in S]
# auto: filings referenced in money-flows / orgs
fl=list(csv.DictReader(open('money-flows.csv')))
seen=set(r['url'] for r in rows)
fil=collections.defaultdict(set)
for r in fl:
    u=r['source_url']
    if u in seen: continue
    if 'propublica' in u: fil[u].add(r['funder']+' ('+(r['period_end'] or r['year'])+')')
    elif 'opensociety' in u: fil[u].add(r['recipient']+' '+r['year'])
    elif 'fec.gov' in u: fil[u].add(r['funder']+' -> '+r['recipient'])
    elif 'usaspending' in u: fil[u].add(r['recipient'])
for u,d in sorted(fil.items()):
    t='IRS Form 990 filing (ProPublica e-file render)' if 'propublica' in u else 'OSF grant record' if 'opensociety' in u else 'FEC committee page' if 'fec.gov' in u else 'USASpending award'
    rows.append(dict(id='auto-%d'%len(rows),title=t+': '+'; '.join(sorted(d))[:200],type=t,publisher_or_agency='IRS via ProPublica' if 'propublica' in u else 'Open Society Foundations' if 'opensociety' in u else 'FEC' if 'fec.gov' in u else 'USASpending.gov',date='',url=u,supports='rows in money-flows.csv',classification=P))
for r in csv.DictReader(open('orgs.csv')):
    u=r['propublica_url']
    if u and u not in seen and u not in fil:
        rows.append(dict(id='org-'+r['ein'],title='ProPublica Nonprofit Explorer org page: '+r['name'],type='IRS filing mirror',publisher_or_agency='IRS via ProPublica',date='',url=u,supports='orgs.csv revenue',classification=P)); seen.add(u)
w=csv.DictWriter(open('sources.csv','w',newline=''),fieldnames=list(rows[0].keys())+['http_status_checked'])
w.writeheader()
st=json.load(open('raw/urlstatus.json')) if __import__('os').path.exists('raw/urlstatus.json') else {}
for r in rows: r['http_status_checked']=st.get(r['url'],''); w.writerow(r)
print(len(rows))
